[reference]
name = "DADAO"
repository = "https://github.com/gxt/DADAO.git"
path = ".work/DADAO"
commit = "f9bde0481668ffab325db8d8c5d8c4cc791c6232"
description = "各阶段早期的代码实现（已不再更新；与 DADAO-0628 无上下游关系）"
