#!/usr/bin/env python3
"""Generate misc.yaml test vectors for TESTCASES-007t.

Covers the M1 identity in tests/vectors/isa/misc.yaml:
  - swym_oiii_imm (oiii): encoding + semantic (nop-like, no architectural state change)

Spec-first: all encoding words, expected values, and spec_cite derived from
contracts/opcodes.yaml, .tao/knowledge/contract-isa.md §13,
contracts/legality_rules.yaml (encode_sbz rule), and
.tao/adr/adr-0004-test-machine.md.

Encoding derivations (ADR-0012 D3.5: MISC-AMO 子表调整):
  - swym 0: op=0x77, ha=0x22, immu18=0 → word=0x77880000
    mask=0xFFFC0000, value=0x77880000 → (0x77880000 & 0xFFFC0000)==0x77880000 ✓

Note: 原专门非法指令已于 ADR-0012 D3.5 删除（ILLI 异常保留）；
fence (oiii) is scope: excluded per SPEC-039t (decode: ILLI)。
"""

import os
import sys

# REPO derived from this file's location (tools/testcases/generate_misc.py)
REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT_DIR = os.path.join(REPO, "tests", "vectors", "isa")
OUT_FILE = os.path.join(OUT_DIR, "misc.yaml")

GENERATOR_PATH = "tools/testcases/generate_misc.py"

# ── Encoding words (ADR-0012 D3.5: swym ha 0x02→0x22) ────────────────
SWYM_WORD0 = 0x77880000       # swym 0 (nop): op=0x77, ha=0x22, immu18=0

MASK_SWYM = 0xFFFC0000
VALUE_SWYM = 0x77880000


def _hex8(w):
    return "0x%08X" % w


def _verify(word, mask, value):
    assert (word & mask) == value, \
        "encoding verification failed: (0x%08X & 0x%08X) != 0x%08X" % (word, mask, value)


# Verify all encodings before generating
_verify(SWYM_WORD0, MASK_SWYM, VALUE_SWYM)


def _case(mnemonic, insn, fmt, cls, word, input_state, expected_state,
          expected_fault=None, expected_pc=None, spec_cite="", notes="",
          status="active", deferred_reason=None):
    return {
        "mnemonic": mnemonic,
        "id": insn,
        "format": fmt,
        "class": cls,
        "encoding": {"word": _hex8(word)},
        "input_state": input_state,
        "expected_state": expected_state,
        "expected_pc": expected_pc,
        "expected_fault": expected_fault,
        "status": status,
        "deferred_reason": deferred_reason,
        "spec_cite": spec_cite,
        "notes": notes,
    }


def generate():
    cases = []

    # ── swym_oiii_imm ─────────────────────────────────────────────────────
    # F10: encoding case — word matches mask/value, decodable, no fault
    cases.append(_case(
        mnemonic="swym",
        insn="swym_oiii_imm",
        fmt="oiii",
        cls="encoding",
        word=SWYM_WORD0,
        input_state={},
        expected_state=None,
        expected_fault=None,
        expected_pc=None,
        spec_cite="SimRISC-11 §占位指令",
        notes="encoding: swym 0 (nop), word=0x77880000; "
              "opcodes.yaml mask=0xFFFC0000 value=0x77880000; "
              "no fault, no architectural state change",
    ))

    # F10: semantic case — nop-like, no state change
    cases.append(_case(
        mnemonic="swym",
        insn="swym_oiii_imm",
        fmt="oiii",
        cls="semantic",
        word=SWYM_WORD0,
        input_state={},
        expected_state={},
        expected_fault=None,
        expected_pc=None,
        spec_cite="SimRISC-11 §占位指令",
        notes="semantic: swym 0 (nop); "
              "除 PC 自增外无任何架构副作用（§7.1）; "
              "expected_state={}: no registers/memory changed",
    ))

    # ── 原专门非法指令已于 ADR-0012 D3.5 删除（ILLI 异常保留）→ 不再产该向量 ──

    return cases


def write_yaml(cases):
    """Write misc.yaml with a header pointing to this generator."""
    import yaml

    header = (
        "# Generated by %s — DO NOT EDIT\n"
        "# Source: contracts/opcodes.yaml + contract-isa.md §13 "
        "+ legality_rules.yaml (encode_sbz)\n"
        "# Each case has spec_cite and notes for traceability.\n"
        "# Covers: swym_oiii_imm (oiii) — 1 M1 identity\n"
        "# ADR-0012 D3.5: 原专门非法指令删除（ILLI 异常保留）→ 无对应向量\n"
        "# F10: swym encoding words verified against opcodes.yaml mask/value\n"
        "# Note: fence is scope: excluded per SPEC-039t (decode: ILLI)\n"
    ) % GENERATOR_PATH

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT_FILE, "w") as f:
        f.write(header)
        yaml.dump(cases, f, default_flow_style=False, sort_keys=False,
                  allow_unicode=True, width=120)


def main():
    cases = generate()
    print("Generated %d cases for misc.yaml:" % len(cases))
    for i, c in enumerate(cases):
        print("  [%d] %s %s %s" % (i, c["id"], c["format"], c["class"]))
    write_yaml(cases)
    print("Written to: %s" % OUT_FILE)


if __name__ == "__main__":
    main()
