#!/usr/bin/env python3
"""Generate misc.yaml test vectors for TESTCASES-007t.

Covers 2 M1 identities in tests/vectors/isa/misc.yaml:
  - swym_oiii_imm (oiii): encoding + semantic (nop-like, no architectural state change)
  - illi (oiii): legality only (always ILLI; encoding/semantic exempt per F6)

Spec-first: all encoding words, expected values, and spec_cite derived from
contracts/opcodes.yaml, .tao/knowledge/contract-isa.md §7/§8/§9,
contracts/legality_rules.yaml (encode_sbz rule), and
.tao/adr/adr-0004-test-machine.md.

Encoding derivations (SPEC-068t: MISC-AMO op 0x00→0x77):
  - swym 0: op=0x77, ha=0x02, immu18=0 → word=0x77080000
    mask=0xFFFC0000, value=0x77080000 → (0x77080000 & 0xFFFC0000)==0x77080000 ✓
  - illi 0: op=0x77, ha=0x00, immu18=0 → word=0x77000000
    mask=0xFFFC0000, value=0x77000000 → (0x77000000 & 0xFFFC0000)==0x77000000 ✓

Note: fence (oiii) is scope: excluded per SPEC-039t (decode: ILLI).
"""

import os
import sys

# REPO derived from this file's location (tools/testcases/generate_misc.py)
REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT_DIR = os.path.join(REPO, "tests", "vectors", "isa")
OUT_FILE = os.path.join(OUT_DIR, "misc.yaml")

GENERATOR_PATH = "tools/testcases/generate_misc.py"

# ── Encoding words (SPEC-068t: MISC-AMO op 0x00→0x77) ────────────────
SWYM_WORD0 = 0x77080000       # swym 0 (nop): op=0x77, ha=0x02, immu18=0
ILLI_WORD0 = 0x77000000       # illi 0: op=0x77, ha=0x00, immu18=0 (always ILLI)

MASK_SWYM = 0xFFFC0000
VALUE_SWYM = 0x77080000
MASK_OIII = 0xFFFC0000
VALUE_ILLI = 0x77000000


def _hex8(w):
    return "0x%08X" % w


def _verify(word, mask, value):
    assert (word & mask) == value, \
        "encoding verification failed: (0x%08X & 0x%08X) != 0x%08X" % (word, mask, value)


# Verify all encodings before generating
_verify(SWYM_WORD0, MASK_SWYM, VALUE_SWYM)
_verify(ILLI_WORD0, MASK_OIII, VALUE_ILLI)


def _case(mnemonic, insn, fmt, cls, word, input_state, expected_state,
          expected_fault=None, expected_pc=None, spec_cite="", notes="",
          status="active", deferred_reason=None):
    return {
        "mnemonic": mnemonic,
        "id": insn,
        "format": fmt,
        "class": cls,
        "encoding": {"word": _hex8(word)},
        "input_state": input_state,
        "expected_state": expected_state,
        "expected_pc": expected_pc,
        "expected_fault": expected_fault,
        "status": status,
        "deferred_reason": deferred_reason,
        "spec_cite": spec_cite,
        "notes": notes,
    }


def generate():
    cases = []

    # ── swym_oiii_imm ─────────────────────────────────────────────────────
    # F10: encoding case — word matches mask/value, decodable, no fault
    cases.append(_case(
        mnemonic="swym",
        insn="swym_oiii_imm",
        fmt="oiii",
        cls="encoding",
        word=SWYM_WORD0,
        input_state={},
        expected_state=None,
        expected_fault=None,
        expected_pc=None,
        spec_cite="SimRISC-11 §占位指令",
        notes="encoding: swym 0 (nop), word=0x77080000; "
              "opcodes.yaml mask=0xFFFC0000 value=0x77080000; "
              "no fault, no architectural state change",
    ))

    # F10: semantic case — nop-like, no state change
    cases.append(_case(
        mnemonic="swym",
        insn="swym_oiii_imm",
        fmt="oiii",
        cls="semantic",
        word=SWYM_WORD0,
        input_state={},
        expected_state={},
        expected_fault=None,
        expected_pc=None,
        spec_cite="SimRISC-11 §占位指令",
        notes="semantic: swym 0 (nop); "
              "除 PC 自增外无任何架构副作用（§7.1）; "
              "expected_state={}: no registers/memory changed",
    ))

    # ── illi (oiii) ───────────────────────────────────────────────────
    # F6: illi is always ILLI → encoding/semantic exempt; coverage via legality
    cases.append(_case(
        mnemonic="illi",
        insn="illi_oiii_imm",
        fmt="oiii",
        cls="legality",
        word=ILLI_WORD0,
        input_state={},
        expected_state=None,
        expected_fault="ILLI",
        expected_pc=None,
        spec_cite="SimRISC-11 §非法指令; SimRISC-00 §MISC-AMO 指令编码",
        notes="illi always triggers ILLI (§9.1); "
              "encoding/semantic exempt per F6 (schema.md §encoding 类对恒 fault 指令的豁免); "
              "this word=0x77000000 is illi 0 (op=0x77); "
              "coverage for (illi, oiii) satisfied by this legality case",
    ))

    return cases


def write_yaml(cases):
    """Write misc.yaml with a header pointing to this generator."""
    import yaml

    header = (
        "# Generated by %s — DO NOT EDIT\n"
        "# Source: contracts/opcodes.yaml + contract-isa.md §7/§8/§9 "
        "+ legality_rules.yaml (encode_sbz)\n"
        "# Each case has spec_cite and notes for traceability.\n"
        "# Covers: swym_oiii_imm (oiii), illi_oiii_imm (oiii) — 2 M1 identities\n"
        "# F6: illi encoding/semantic exempt (always ILLI), coverage via legality\n"
        "# F10: swym encoding words verified against opcodes.yaml mask/value\n"
        "# Note: fence is scope: excluded per SPEC-039t (decode: ILLI)\n"
    ) % GENERATOR_PATH

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT_FILE, "w") as f:
        f.write(header)
        yaml.dump(cases, f, default_flow_style=False, sort_keys=False,
                  allow_unicode=True, width=120)


def main():
    cases = generate()
    print("Generated %d cases for misc.yaml:" % len(cases))
    for i, c in enumerate(cases):
        print("  [%d] %s %s %s" % (i, c["id"], c["format"], c["class"]))
    write_yaml(cases)
    print("Written to: %s" % OUT_FILE)


if __name__ == "__main__":
    main()
