#!/usr/bin/env python3
"""Generate ctrl-jump.yaml, ctrl-call.yaml, ctrl-ret.yaml for TESTCASES-006t.

Covers all 5 M1 identities (jump-iiii, jump-rrii, call-iiii, call-rrii, ret-riii) with:
  - encoding cases (jump/call only; ret-riii excluded: return target depends on harness layout)
  - semantic cases with expected_pc (+ expected_state.ra for call/ret)
  - legality cases (UNMAPPED, RASOF, RASUF)

Spec-first: all encoding words, expected values, and spec_cite derived from
contracts/opcodes.yaml, .tao/knowledge/contract-isa.md §5.3–§5.6, and
.tao/knowledge/adr-0004-test-machine.md (D6.5: rb0 = current instruction address,
D2.1: cold RA ra0–ra63 = 0, D5.6: unmapped fault).

PC convention: instruction address = 0xffff_0000_0000 (RAM entry, ADR-0004 D2.2).
imm=2 for jump/call → target = rb0 + 8 = 0xffff00000008.
Return address for call = PC+4 = 0xffff00000004.

call §5.6.1 semantic coverage:
  - case 1 (cold RA): ra63 invalid → new address pushed, count=0x0001
  - case 2 (recursive): ra63 valid, PC+4 == ra63 low 48 → count +1
  - case 3 (shift-push): ra63 valid, PC+4 ≠ ra63 low 48 → shift-down
"""

import os
import sys

try:
    import yaml
except ImportError:
    sys.exit("ERROR: PyYAML 未安装。运行: pip install pyyaml")

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT_DIR = os.path.join(REPO, "tests", "vectors", "isa")

# ── Load opcodes (for validation only) ────────────────────────────────
with open(os.path.join(REPO, "contracts", "opcodes.yaml")) as f:
    ALL = yaml.safe_load(f)

BY_KEY = {}
for r in ALL:
    if not r.get("excluded_m1"):
        BY_KEY[(r["insn"], r["format"])] = r

# ── Constants ─────────────────────────────────────────────────────────
RB0 = 0xFFFF_0000_0000          # instruction address (ADR-0004 D2.2/D6.5)
IMM = 2                         # imm for jump/call (not 0, not 1)
TARGET = "0x%012X" % (RB0 + (IMM << 2))     # 0xFFFF00000008
RETURN_ADDR = "0x%012X" % (RB0 + 4)          # 0xFFFF00000004
RA64_FMT = "0x%016X"            # 64-bit hex for RA registers

# ── Encoding word builders ────────────────────────────────────────────
def _build_word_iiii(op, imm24):
    """iiii format: op[31:24] | imms24[23:0]."""
    return (op << 24) | (imm24 & 0xFFFFFF)

def _build_word_rrii(op, ha, hb, imm12):
    """rrii format: op[31:24] | ha[23:18] | hb[17:12] | imms12[11:0]."""
    return (op << 24) | (ha << 18) | (hb << 12) | (imm12 & 0xFFF)

def _build_word_riii(op, ha, imm18):
    """riii format: op[31:24] | ha[23:18] | imms18[17:0]."""
    return (op << 24) | (ha << 18) | (imm18 & 0x3FFFF)

def _hex8(w):
    """Format 32-bit word as 0x-prefixed uppercase 8-char hex."""
    return "0x%08X" % w

# ── Case factory ──────────────────────────────────────────────────────
def _case(cls, insn, fmt, word, inp, out, fault=None,
          expected_pc=None, spec_cite="", notes=""):
    return {
        "class": cls,
        "deferred_reason": None,
        "encoding": {"word": _hex8(word)},
        "expected_fault": fault,
        "expected_pc": expected_pc,
        "expected_state": out,
        "format": fmt,
        "input_state": inp,
        "insn": insn,
        "mnemonic": insn.split("-")[0],
        "notes": notes,
        "spec_cite": spec_cite,
        "status": "active",
    }

# ── Header ────────────────────────────────────────────────────────────
HEADER_JUMP = """\
# Generated by TESTCASES-006t generator — DO NOT EDIT
# Source: contracts/opcodes.yaml + contract-isa.md §5.3 + adr-0004 D6.5
# Each case has spec_cite and notes for traceability.
# PC convention: instruction address = 0xffff_0000_0000 (RAM entry, ADR-0004 D2.2)
# imm=2 for jump → target = rb0 + 8 = 0xffff00000008
# jump-rrii uses ha=rb0, hb=rd0, imms12=2 for semantic; ha=rb3 (0) for UNMAPPED legality
"""

HEADER_CALL = """\
# Generated by TESTCASES-006t generator — DO NOT EDIT
# Source: contracts/opcodes.yaml + contract-isa.md §5.4/§5.6 + adr-0004 D6.5
# Each case has spec_cite and notes for traceability.
# PC convention: instruction address = 0xffff_0000_0000 (RAM entry, ADR-0004 D2.2)
# imm=2 for call → target = rb0 + 8 = 0xffff00000008; return address = PC+4 = 0xffff00000004
# call-rrii uses ha=rb0, hb=rd0, imms12=2 for semantic; ha=rb3 (0) for UNMAPPED legality
# RASOF legality: pre-set ra1-ra63 as valid (high 16=0x0001, low 48=0) to trigger overflow
"""

HEADER_RET = """\
# Generated by TESTCASES-006t generator — DO NOT EDIT
# Source: contracts/opcodes.yaml + contract-isa.md §5.5/§5.6 + adr-0004 D6.5
# Each case has spec_cite and notes for traceability.
# PC convention: instruction address = 0xffff_0000_0000 (RAM entry, ADR-0004 D2.2)
# ret rd0, 0 is legal (rd0 as destination allowed)
# ret-riii no encoding case: return target depends on harness layout, single instruction cannot construct
# RASUF legality: cold RA (ra0-ra63=0) → pop underflow → RASUF (0x8B)
"""

# ── Spec cites ────────────────────────────────────────────────────────
SC_JUMP = "SimRISC-02 §无条件跳转指令; ADR-0004 D6.5"
SC_JUMP_LEG = "SimRISC-02 §无条件跳转指令; ADR-0004 D5.6"
SC_CALL = "SimRISC-02 §函数调用; ADR-0004 D6.5"
SC_CALL_SEM = "SimRISC-02 §函数调用; §5.6.1; ADR-0004 D2.1"
SC_CALL_RASOF = "SimRISC-02 §函数调用; §5.6.1; ADR-0004 D5.5"
SC_CALL_LEG = "SimRISC-02 §函数调用; ADR-0004 D5.6"
SC_RET = "SimRISC-02 §函数返回; §5.6.2; ADR-0004 D6.5"
SC_RET_LEG = "SimRISC-02 §函数返回; §5.6.2; ADR-0004 D5.5"


# ── jump-iiii ─────────────────────────────────────────────────────────
def _gen_jump_iiii():
    op = int(BY_KEY[("jump-iiii", "iiii")]["op"], 16)
    word = _build_word_iiii(op, IMM)
    # Boundary: imms24 = -0x1000 → target = RB0 + (-4096 << 2) = RB0 - 0x4000
    # = 0xFFFE_FFFF_C000 (48-bit valid, below RAM → UNMAPPED)
    boundary_imm = (-0x1000) & 0xFFFFFF  # 24-bit signed
    boundary_word = _build_word_iiii(op, boundary_imm)
    imm_s = boundary_imm - (1 << 24) if boundary_imm & (1 << 23) else boundary_imm
    target_boundary = "0x%012X" % ((RB0 + (imm_s << 2)) & 0xFFFFFFFFFFFF)
    return [
        _case("encoding", "jump-iiii", "iiii", word, {}, None,
              None, None, SC_JUMP,
              "encoding: word matches opcodes.yaml mask/value, imms24=2 "
              "(non-zero, non-self-jump)"),
        _case("semantic", "jump-iiii", "iiii", word, {}, {},
              None, TARGET, SC_JUMP,
              "semantic: rb0=0xFFFF00000000 (RAM entry, ADR-0004 D2.2), "
              "imms24=2, Addr=rb0+(imms24<<2)=0xFFFF00000000+8="
              "0xFFFF00000008; no state change"),
        _case("boundary", "jump-iiii", "iiii", boundary_word, {}, {},
              "UNMAPPED", None, SC_JUMP_LEG,
              "boundary UNMAPPED: imms24=-0x1000, "
              "target=rb0+(imms24<<2)=0x%012X+(-0x4000)=0x%012X → "
              "beyond RAM (0xFFFF_00FF_FFFF) → UNMAPPED (0x87)"
              % (RB0, int(target_boundary, 16))),
    ]


# ── jump-rrii ─────────────────────────────────────────────────────────
def _gen_jump_rrii():
    op = int(BY_KEY[("jump-rrii", "rrii")]["op"], 16)
    enc_word = _build_word_rrii(op, 0, 0, IMM)      # ha=rb0, hb=rd0
    unmapped_word = _build_word_rrii(op, 3, 0, 0)    # ha=rb3=0 → addr=0
    return [
        _case("encoding", "jump-rrii", "rrii", enc_word, {}, None,
              None, None, SC_JUMP,
              "encoding: word matches opcodes.yaml mask/value, rbha=rb0 "
              "(index 0), rdhb=rd0 (index 0), imms12=2"),
        _case("semantic", "jump-rrii", "rrii", enc_word, {}, {},
              None, TARGET, SC_JUMP,
              "semantic: rb0=0xFFFF00000000, rd0=0, imms12=2, "
              "Addr=rb0+rd0+(imms12<<2)=0xFFFF00000000+0+8="
              "0xFFFF00000008; no state change"),
        _case("legality", "jump-rrii", "rrii", unmapped_word,
              {"rb": {"rb3": "0x0000000000000000"}}, None,
              "UNMAPPED", None, SC_JUMP_LEG,
              "legality UNMAPPED: rbha=rb3=0, rdhb=rd0=0, imms12=0 → "
              "addr=0 → unmapped (0x87), ADR-0004 D5.6"),
    ]


# ── call-iiii ─────────────────────────────────────────────────────────
def _gen_call_iiii():
    op = int(BY_KEY[("call-iiii", "iiii")]["op"], 16)
    word = _build_word_iiii(op, IMM)

    # §5.6.1 case 3 input: ra1-ra63 valid (count=1, addr=0)
    # When shift-push occurs, ra1 valid and ra0 low48=0 → RASOF
    # Use explicit loop for numerical ordering (not alphabetical)
    ra_overflow = {}
    for i in range(1, 64):
        ra_overflow["ra%d" % i] = RA64_FMT % 0x0001_0000_0000_0000

    return [
        _case("encoding", "call-iiii", "iiii", word, {}, None,
              None, None, SC_CALL,
              "encoding: word matches opcodes.yaml mask/value, imms24=2 "
              "(non-zero, non-self-call)"),
        # §5.6.1 case 1: cold RA → new address pushed, count=0x0001
        _case("semantic", "call-iiii", "iiii", word, {},
              {"ra": {"ra63": RA64_FMT % ((1 << 48) | (RB0 + 4))}},
              None, TARGET, SC_CALL_SEM,
              "semantic: rb0=0xFFFF00000000, imms24=2, "
              "Addr=rb0+(imms24<<2)=0xFFFF00000000+8=0xFFFF00000008; "
              "call pushes return address PC+4=0xFFFF00000004 into ra63, "
              "high 16=0x0001 (first push), low 48=return address; "
              "cold RA (ra0-ra63=0) per ADR-0004 D2.1"),
        # §5.6.1 case 2: recursive → count +1
        _case("semantic", "call-iiii", "iiii", word,
              {"ra": {"ra63": RA64_FMT % ((1 << 48) | (RB0 + 4))}},
              {"ra": {"ra63": RA64_FMT % ((2 << 48) | (RB0 + 4))}},
              None, TARGET, SC_CALL_SEM,
              "semantic §5.6.1 case 2 (recursive): rb0=0xFFFF00000000, "
              "imms24=2, Addr=0xFFFF00000008; ra63 input high 16=0x0001 "
              "(valid), low 48=0xFFFF00000004; PC+4=0xFFFF00000004 == "
              "ra63 low 48 → count +1: ra63 = 0x0002FFFF00000004"),
        # §5.6.1 case 3: shift-push (RASOF legality)
        _case("legality", "call-iiii", "iiii", word,
              {"ra": ra_overflow}, None,
              "RASOF", None, SC_CALL_RASOF,
              "legality RASOF: pre-set ra1-ra63 as valid (high 16=0x0001, "
              "low 48=0), ra0=0 (only RegRAS); call triggers shift-push, "
              "ra1 valid and ra0 low 48=0 → RASOF (0x8A), contract-isa §5.6.1"),
    ]


# ── call-rrii ─────────────────────────────────────────────────────────
def _gen_call_rrii():
    op = int(BY_KEY[("call-rrii", "rrii")]["op"], 16)
    enc_word = _build_word_rrii(op, 0, 0, IMM)      # ha=rb0, hb=rd0
    unmapped_word = _build_word_rrii(op, 3, 0, 0)    # ha=rb3=0 → addr=0
    return [
        _case("encoding", "call-rrii", "rrii", enc_word, {}, None,
              None, None, SC_CALL,
              "encoding: word matches opcodes.yaml mask/value, rbha=rb0 "
              "(index 0), rdhb=rd0 (index 0), imms12=2"),
        # §5.6.1 case 1: cold RA
        _case("semantic", "call-rrii", "rrii", enc_word, {},
              {"ra": {"ra63": RA64_FMT % ((1 << 48) | (RB0 + 4))}},
              None, TARGET, SC_CALL_SEM,
              "semantic: rb0=0xFFFF00000000, rd0=0, imms12=2, "
              "Addr=rb0+rd0+(imms12<<2)=0xFFFF00000000+0+8="
              "0xFFFF00000008; call pushes return address "
              "PC+4=0xFFFF00000004 into ra63, high 16=0x0001, "
              "low 48=return address; cold RA per ADR-0004 D2.1"),
        # §5.6.1 case 2: recursive → count +1
        _case("semantic", "call-rrii", "rrii", enc_word,
              {"ra": {"ra63": RA64_FMT % ((1 << 48) | (RB0 + 4))}},
              {"ra": {"ra63": RA64_FMT % ((2 << 48) | (RB0 + 4))}},
              None, TARGET, SC_CALL_SEM,
              "semantic §5.6.1 case 2 (recursive): rb0=0xFFFF00000000, "
              "rd0=0, imms12=2, Addr=0xFFFF00000008; ra63 input "
              "high 16=0x0001 (valid), low 48=0xFFFF00000004; "
              "PC+4=0xFFFF00000004 == ra63 low 48 → count +1: "
              "ra63 = 0x0002FFFF00000004"),
        # §5.6.1 case 3: shift-push (different address)
        _case("semantic", "call-rrii", "rrii", enc_word,
              {"ra": {"ra63": RA64_FMT % ((1 << 48) | 0xAAAA_0000_0000)}},
              {"ra": {
                  "ra63": RA64_FMT % ((1 << 48) | (RB0 + 4)),
                  "ra62": RA64_FMT % ((1 << 48) | 0xAAAA_0000_0000),
              }},
              None, TARGET, SC_CALL_SEM,
              "semantic §5.6.1 case 3 (shift-push): rb0=0xFFFF00000000, "
              "rd0=0, imms12=2, Addr=0xFFFF00000008; ra63 input "
              "high 16=0x0001 (valid), low 48=0xAAAA000000000000; "
              "PC+4=0xFFFF00000004 ≠ ra63 low 48 → shift-push: "
              "new addr into ra63, old ra63 into ra62"),
        _case("legality", "call-rrii", "rrii", unmapped_word,
              {"rb": {"rb3": "0x0000000000000000"}}, None,
              "UNMAPPED", None, SC_CALL_LEG,
              "legality UNMAPPED: rbha=rb3=0, rdhb=rd0=0, imms12=0 → "
              "addr=0 → unmapped (0x87), ADR-0004 D5.6"),
    ]


# ── ret-riii ──────────────────────────────────────────────────────────
def _gen_ret_riii():
    op = int(BY_KEY[("ret-riii", "riii")]["op"], 16)
    word = _build_word_riii(op, 0, 0)  # rdha=rd0, imms18=0
    return [
        # §5.6.2 case 2: pop (count=1 → shift-down)
        _case("semantic", "ret-riii", "riii", word,
              {"ra": {"ra63": RA64_FMT % ((1 << 48) | (RB0 + 4))}},
              {"ra": {"ra63": RA64_FMT % 0}},
              None, RETURN_ADDR, SC_RET,
              "semantic: ret rd0, 0; ra63=0x0001FFFF00000004 "
              "(high 16=0x0001, low 48=0xFFFF00000004); "
              "PC = ra63 low 48 = 0xFFFF00000004; "
              "rd0 = sign_extend(0) = 0 (rd0恒零); "
              "弹栈: ra63 high 16=0x0001 → case 2: pop, shift-down: "
              "ra62→ra63 (ra62=0→ra63=0), ra1→ra2 (ra1=0→ra2=0), "
              "ra1清0 → ra63=0; expected_state.ra.ra63=0"),
        # §5.6.2 case 3: RASUF (cold RA, pop underflow)
        _case("legality", "ret-riii", "riii", word, {}, None,
              "RASUF", None, SC_RET_LEG,
              "legality RASUF: cold RA (ra0-ra63=0), ra63 high 16=0 "
              "(无效), ra0 low 48=0 (only RegRAS) → pop underflow → "
              "RASUF (0x8B), contract-isa §5.6.2 case 3"),
    ]


# ── Write YAML ────────────────────────────────────────────────────────
def _write_yaml(filename, header, cases):
    path = os.path.join(OUT_DIR, filename)
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(path, "w") as f:
        f.write(header)
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True,
                  width=120)
    n_enc = sum(1 for c in cases if c["class"] == "encoding")
    n_sem = sum(1 for c in cases if c["class"] == "semantic")
    n_leg = sum(1 for c in cases if c["class"] == "legality")
    print("Wrote %s: %d cases (%d encoding, %d semantic, %d legality)" % (
        path, len(cases), n_enc, n_sem, n_leg))


# ── Main ──────────────────────────────────────────────────────────────
def main():
    jump_cases = _gen_jump_iiii() + _gen_jump_rrii()
    call_cases = _gen_call_iiii() + _gen_call_rrii()
    ret_cases = _gen_ret_riii()

    _write_yaml("ctrl-jump.yaml", HEADER_JUMP, jump_cases)
    _write_yaml("ctrl-call.yaml", HEADER_CALL, call_cases)
    _write_yaml("ctrl-ret.yaml", HEADER_RET, ret_cases)

    total = len(jump_cases) + len(call_cases) + len(ret_cases)
    print("\nTotal: %d cases across 3 files" % total)
    print("Identities covered: jump-iiii, jump-rrii, call-iiii, call-rrii, ret-riii")
    return 0


if __name__ == "__main__":
    sys.exit(main())
