#!/usr/bin/env python3
"""Generate ctrl-jump.yaml, ctrl-call.yaml, ctrl-ret.yaml.

Covers M1 identities (jump-iiii, jump-rrii, call-iiii, call-rrii, ret-riii) with:
  - encoding cases (jump/call only; ret-riii excluded: return target depends on harness layout)
  - semantic/boundary cases with expected_pc, expected_state (ra + memory)
  - legality cases (UNMAPPED, RASOF, RASUF)

Spec-first: all encoding words, expected values, and spec_cite derived from
contracts/opcodes.yaml, spec/SimRISC-00 §返回地址栈 (D7),
spec/SimRISC-06 §函数调用|§函数返回, and
.tao/adr/adr-0004-test-machine.md (D2.1, D5.5, D5.6, D6.5).

RA semantics (ADR-0012 D7):
  - ra0[53:48] = RACNT (valid entry count, 0–63); ra0[47:0] = MRPTR (MemRAS top address, 0=no MemRAS)
  - ra1–ra63: [63:48] = recursive count, [47:0] = return address; ra63 = stack top
  - Validity determined by RACNT, NOT by individual entry values
  - Full-stack overflow: RACNT==63, MRPTR==0 → RASOF; MRPTR!=0 → spill oldest to MemRAS, keep RACNT=63
  - Pop underflow: RACNT==0, MRPTR==0 → RASUF; RACNT==0, MRPTR!=0 → read MemRAS entry

PC convention: instruction address = 0xffff_0000_0000 (RAM entry, ADR-0004 D2.2).
imm=2 for jump/call → target = rb0 + 8 = 0xffff00000008.
Return address for call = PC+4 = 0xffff00000004.
"""

import os
import sys

try:
    import yaml
except ImportError:
    sys.exit("ERROR: PyYAML 未安装。运行: pip install pyyaml")

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT_DIR = os.path.join(REPO, "tests", "vectors", "isa")

# ── Load opcodes (for validation only) ────────────────────────────────
with open(os.path.join(REPO, "contracts", "opcodes.yaml")) as f:
    ALL = yaml.safe_load(f)

BY_KEY = {}
for r in ALL:
    if not r.get("excluded_m1"):
        BY_KEY[(r["id"], r["format"])] = r

# ── Constants ─────────────────────────────────────────────────────────
RB0 = 0xFFFF_0000_0000          # instruction address (ADR-0004 D2.2/D6.5)
IMM = 2                         # imm for jump/call (not 0, not 1)
TARGET = "0x%012X" % (RB0 + (IMM << 2))     # 0xFFFF00000008
RETURN_ADDR = "0x%012X" % (RB0 + 4)          # 0xFFFF00000004
RA64_FMT = "0x%016X"            # 64-bit hex for RA registers
HEX48_FMT = "0x%012X"           # 48-bit hex for MRPTR / addresses

# MemRAS test addresses (in RAM, 8-byte aligned, within 0xFFFF00000000–0xFFFF00FFFFFF)
MRPTR_BASE = 0xFFFF_00F0_0000   # MemRAS base for test cases (within RAM window)

# ── ra0 helpers (D7 bit layout) ───────────────────────────────────────
def _ra0(racnt, mrptr):
    """Encode ra0: [53:48]=RACNT, [47:0]=MRPTR."""
    return RA64_FMT % ((racnt & 0x3F) << 48 | (mrptr & 0xFFFFFFFFFFFF))


# ── Encoding word builders ────────────────────────────────────────────
def _build_word_iiii(op, imm24):
    """iiii format: op[31:24] | imms24[23:0]."""
    return (op << 24) | (imm24 & 0xFFFFFF)

def _build_word_rrii(op, ha, hb, imm12):
    """rrii format: op[31:24] | ha[23:18] | hb[17:12] | imms12[11:0]."""
    return (op << 24) | (ha << 18) | (hb << 12) | (imm12 & 0xFFF)

def _build_word_riii(op, ha, imm18):
    """riii format: op[31:24] | ha[23:18] | imms18[17:0]."""
    return (op << 24) | (ha << 18) | (imm18 & 0x3FFFF)

def _hex8(w):
    """Format 32-bit word as 0x-prefixed uppercase 8-char hex."""
    return "0x%08X" % w

# ── Case factory ──────────────────────────────────────────────────────
def _case(cls, insn, fmt, word, inp, out, fault=None,
          expected_pc=None, spec_cite="", notes=""):
    # Extract mnemonic from new id format: mnemonic_format_bank
    if '_' in insn:
        _FORMATS = ('orrr', 'orri', 'rrrr', 'riii', 'rrii', 'rwii', 'iiii', 'rrri', 'oiii')
        parts = insn.split('_')
        if len(parts) >= 3 and parts[-2] in _FORMATS:
            mnem = '_'.join(parts[:-2])
        else:
            mnem = parts[0]
    else:
        mnem = insn.split("-")[0]
    return {
        "class": cls,
        "deferred_reason": None,
        "encoding": {"word": _hex8(word)},
        "expected_fault": fault,
        "expected_pc": expected_pc,
        "expected_state": out,
        "format": fmt,
        "input_state": inp,
        "id": insn,
        "mnemonic": mnem,
        "notes": notes,
        "spec_cite": spec_cite,
        "status": "active",
    }


# ── Header ────────────────────────────────────────────────────────────
HEADER_JUMP = """\
# Generated by TESTCASES-020t generator — DO NOT EDIT
# Source: contracts/opcodes.yaml + SimRISC-06 §无条件跳转 + ADR-0004 D6.5
# Each case has spec_cite and notes for traceability.
# PC convention: instruction address = 0xffff_0000_0000 (RAM entry, ADR-0004 D2.2)
# imm=2 for jump → target = rb0 + 8 = 0xffff00000008
# jump-rrii uses ha=rb0, hb=rd0, imms12=2 for semantic; ha=rb3 (0) for UNMAPPED legality
"""

HEADER_CALL = """\
# Generated by TESTCASES-020t generator — DO NOT EDIT
# Source: contracts/opcodes.yaml + SimRISC-00 §返回地址栈 + SimRISC-06 §函数调用
# Each case has spec_cite and notes for traceability.
# RA semantics: ADR-0012 D7 — validity by RACNT (ra0[53:48]), not entry values
# PC convention: instruction address = 0xffff_0000_0000 (RAM entry, ADR-0004 D2.2)
# imm=2 for call → target = rb0 + 8 = 0xffff00000008; return address = PC+4 = 0xffff00000004
# Full-stack RASOF: RACNT=63, MRPTR=0 (no MemRAS)
# MemRAS C3b: RACNT=63, MRPTR!=0 → spill oldest to MemRAS, RACNT stays 63
"""

HEADER_RET = """\
# Generated by TESTCASES-022t generator — DO NOT EDIT
# Source: contracts/opcodes.yaml + SimRISC-00 §返回地址栈 + SimRISC-06 §函数返回
# Each case has spec_cite and notes for traceability.
# RA semantics: ADR-0012 D7 — validity by RACNT (ra0[53:48]), not entry values
# PC convention: instruction address = 0xffff_0000_0000 (RAM entry, ADR-0004 D2.2)
# ret rd0, 0 is legal; ret rd0, imms18!=0 → ILLI (dst_rd0_nonzero, TESTCASES-022t)
# RASUF: RACNT=0, MRPTR=0 → cold RA underflow; D4b MemRAS count=0 → RASUF
"""


# ── Spec cites ────────────────────────────────────────────────────────
SC_JUMP = "SimRISC-06 §无条件跳转指令; ADR-0004 D6.5"
SC_JUMP_LEG = "SimRISC-06 §无条件跳转指令; ADR-0004 D5.6"
SC_CALL = "SimRISC-06 §函数调用; ADR-0004 D6.5"
SC_CALL_C1 = "SimRISC-00 §返回地址栈 §C1; SimRISC-06 §函数调用; ADR-0004 D2.1"
SC_CALL_C2 = "SimRISC-00 §返回地址栈 §C2; SimRISC-06 §函数调用"
SC_CALL_C3a = "SimRISC-00 §返回地址栈 §C3a; SimRISC-06 §函数调用"
SC_CALL_RASOF = "SimRISC-00 §返回地址栈 §C3b; SimRISC-06 §函数调用; ADR-0004 D5.5"
SC_CALL_C3b_MEM = "SimRISC-00 §返回地址栈 §C3b; SimRISC-06 §函数调用"
SC_CALL_LEG = "SimRISC-06 §函数调用; ADR-0004 D5.6"
SC_RET = "SimRISC-06 §函数返回; SimRISC-00 §返回地址栈; ADR-0004 D6.5"
SC_RET_D2 = "SimRISC-00 §返回地址栈 §D2; SimRISC-06 §函数返回"
SC_RET_D3 = "SimRISC-00 §返回地址栈 §D3; SimRISC-06 §函数返回"
SC_RET_D4b = "SimRISC-00 §返回地址栈 §D4b; SimRISC-06 §函数返回"
SC_RET_RASUF = "SimRISC-00 §返回地址栈 §D4a; SimRISC-06 §函数返回; ADR-0004 D5.5"
SC_RET_D4B_RASUF = "SimRISC-00 §返回地址栈 §D4b; SimRISC-06 §函数返回; ADR-0004 D5.5"
# TESTCASES-022t: ret rd0 ⇒ imms18 MUST be 0 (dst_rd0_nonzero); rd != rd0 unconstrained
SC_RET_RD0_IMMS18 = "SimRISC-06 §函数返回; SimRISC-00 §数据寄存器"


# ── jump-iiii (unchanged) ─────────────────────────────────────────────
def _gen_jump_iiii():
    op = int(BY_KEY[("jump_iiii_rb", "iiii")]["op"], 16)
    word = _build_word_iiii(op, IMM)
    boundary_imm = (-0x1000) & 0xFFFFFF
    boundary_word = _build_word_iiii(op, boundary_imm)
    imm_s = boundary_imm - (1 << 24) if boundary_imm & (1 << 23) else boundary_imm
    target_boundary = "0x%012X" % ((RB0 + (imm_s << 2)) & 0xFFFFFFFFFFFF)
    return [
        _case("encoding", "jump_iiii_rb", "iiii", word, {}, None,
              None, None, SC_JUMP,
              "encoding: word matches opcodes.yaml mask/value, imms24=2 "
              "(non-zero, non-self-jump)"),
        _case("semantic", "jump_iiii_rb", "iiii", word, {}, {},
              None, TARGET, SC_JUMP,
              "semantic: rb0=0xFFFF00000000 (RAM entry, ADR-0004 D2.2), "
              "imms24=2, Addr=rb0+(imms24<<2)=0xFFFF00000000+8="
              "0xFFFF00000008; no state change"),
        _case("boundary", "jump_iiii_rb", "iiii", boundary_word, {}, {},
              "UNMAPPED", None, SC_JUMP_LEG,
              "boundary UNMAPPED: imms24=-0x1000, "
              "target=rb0+(imms24<<2)=0x%012X+(-0x4000)=0x%012X → "
              "beyond RAM (0xFFFF_00FF_FFFF) → UNMAPPED (0x87)"
              % (RB0, int(target_boundary, 16))),
    ]


# ── jump-rrii (unchanged) ─────────────────────────────────────────────
def _gen_jump_rrii():
    op = int(BY_KEY[("jump_rrii_rb", "rrii")]["op"], 16)
    enc_word = _build_word_rrii(op, 0, 0, IMM)
    unmapped_word = _build_word_rrii(op, 3, 0, 0)
    return [
        _case("encoding", "jump_rrii_rb", "rrii", enc_word, {}, None,
              None, None, SC_JUMP,
              "encoding: word matches opcodes.yaml mask/value, rbha=rb0 "
              "(index 0), rdhb=rd0 (index 0), imms12=2"),
        _case("semantic", "jump_rrii_rb", "rrii", enc_word, {}, {},
              None, TARGET, SC_JUMP,
              "semantic: rb0=0xFFFF00000000, rd0=0, imms12=2, "
              "Addr=rb0+rd0+(imms12<<2)=0xFFFF00000000+0+8="
              "0xFFFF00000008; no state change"),
        _case("legality", "jump_rrii_rb", "rrii", unmapped_word,
              {"rb": {"rb3": "0x0000000000000000"}}, None,
              "UNMAPPED", None, SC_JUMP_LEG,
              "legality UNMAPPED: rbha=rb3=0, rdhb=rd0=0, imms12=0 → "
              "addr=0 → unmapped (0x87), ADR-0004 D5.6"),
    ]


# ── call-iiii (D7 rewrite) ───────────────────────────────────────────
def _gen_call_iiii():
    op = int(BY_KEY[("call_iiii_ra", "iiii")]["op"], 16)
    word = _build_word_iiii(op, IMM)

    # C1: cold RA → push new entry, RACNT=1
    #   ra0: RACNT 0→1, MRPTR stays 0
    #   ra63: [63:48]=1, [47:0]=PC+4
    c1_out_ra0 = _ra0(1, 0)
    c1_out_ra63 = RA64_FMT % ((1 << 48) | (RB0 + 4))

    # C2: recursive → count +1, RACNT unchanged
    #   input: ra0 has RACNT=1, MRPTR=0; ra63 has count=1, addr=PC+4
    #   output: ra63 count=2, addr=PC+4; ra0 unchanged (RACNT stays 1)
    c2_in_ra0 = _ra0(1, 0)
    c2_in_ra63 = RA64_FMT % ((1 << 48) | (RB0 + 4))
    c2_out_ra63 = RA64_FMT % ((2 << 48) | (RB0 + 4))

    # C3a: shift-push → new entry, RACNT += 1
    #   input: RACNT=1, ra63 count=1, addr=0xAAAA00000000
    #   output: RACNT=2, ra63=[1, PC+4], ra62=[1, 0xAAAA00000000]
    c3a_in_ra0 = _ra0(1, 0)
    c3a_in_ra63 = RA64_FMT % ((1 << 48) | 0xAAAA_0000_0000)
    c3a_out_ra0 = _ra0(2, 0)
    c3a_out_ra63 = RA64_FMT % ((1 << 48) | (RB0 + 4))
    c3a_out_ra62 = RA64_FMT % ((1 << 48) | 0xAAAA_0000_0000)

    # RASOF: RACNT=63, MRPTR=0, different address → C3b → RASOF
    rasof_in_ra0 = _ra0(63, 0)
    # ra63 has a valid entry (count=1, some address) so C2 doesn't match
    rasof_in_ra63 = RA64_FMT % ((1 << 48) | 0xCCCC_0000_0000)

    # C3b MemRAS: RACNT=63, MRPTR!=0 → spill oldest to MemRAS, RACNT stays 63
    #   Oldest entry = ra[64-RACNT] = ra[64-63] = ra1
    #   ra1 has count=5, addr=0xDDDD00000000
    #   Spill ra1 to MRPTR-8, then push new entry, MRPTR-=8
    c3b_mrptr = MRPTR_BASE
    c3b_mrptr_after = "0x%012X" % (c3b_mrptr - 8)
    c3b_in_ra0 = _ra0(63, c3b_mrptr)
    c3b_in_ra1 = RA64_FMT % ((5 << 48) | 0xDDDD_0000_0000)
    c3b_in_ra63 = RA64_FMT % ((1 << 48) | 0xCCCC_0000_0000)
    c3b_out_ra0 = _ra0(63, c3b_mrptr - 8)
    c3b_out_ra63 = RA64_FMT % ((1 << 48) | (RB0 + 4))
    c3b_mem_addr = c3b_mrptr_after
    c3b_mem_val = RA64_FMT % ((5 << 48) | 0xDDDD_0000_0000)

    # Build input dict for RASOF (all 63 ra entries with RACNT=63)
    # Only need ra0 + ra63 in input (RACNT determines validity)
    rasof_inp = {"ra": {"ra0": rasof_in_ra0, "ra63": rasof_in_ra63}}

    # Build input dict for C3b MemRAS
    c3b_inp = {"ra": {"ra0": c3b_in_ra0, "ra1": c3b_in_ra1, "ra63": c3b_in_ra63}}

    return [
        _case("encoding", "call_iiii_ra", "iiii", word, {}, None,
              None, None, SC_CALL,
              "encoding: word matches opcodes.yaml mask/value, imms24=2 "
              "(non-zero, non-self-call)"),
        # C1: cold RA → new address pushed, RACNT 0→1
        _case("semantic", "call_iiii_ra", "iiii", word, {},
              {"ra": {"ra0": c1_out_ra0, "ra63": c1_out_ra63}},
              None, TARGET, SC_CALL_C1,
              "semantic C1: rb0=0xFFFF00000000, imms24=2, "
              "Addr=0xFFFF00000008; cold RA (RACNT=0, MRPTR=0); "
              "push: ra63=[count=1, ret_addr=0xFFFF00000004], RACNT→1; "
              "ra0=%s" % c1_out_ra0),
        # C2: recursive → count +1
        _case("semantic", "call_iiii_ra", "iiii", word,
              {"ra": {"ra0": c2_in_ra0, "ra63": c2_in_ra63}},
              {"ra": {"ra63": c2_out_ra63}},
              None, TARGET, SC_CALL_C2,
              "semantic C2 (recursive fold): ra0=%s, ra63 input "
              "[count=1, addr=0xFFFF00000004]; PC+4=0xFFFF00000004 == "
              "ra63[47:0] → count+1: ra63=[count=2, addr=0xFFFF00000004]; "
              "RACNT unchanged (1)" % c2_in_ra0),
        # C3a: shift-push
        _case("semantic", "call_iiii_ra", "iiii", word,
              {"ra": {"ra0": c3a_in_ra0, "ra63": c3a_in_ra63}},
              {"ra": {
                  "ra0": c3a_out_ra0,
                  "ra63": c3a_out_ra63,
                  "ra62": c3a_out_ra62,
              }},
              None, TARGET, SC_CALL_C3a,
              "semantic C3a (shift-push): ra0=%s, ra63 input "
              "[count=1, addr=0xAAAA00000000]; PC+4=0xFFFF00000004 ≠ "
              "ra63[47:0] → shift-push: new ra63=[1, 0xFFFF00000004], "
              "old ra63→ra62=[1, 0xAAAA00000000]; RACNT→2, ra0=%s"
              % (c3a_in_ra0, c3a_out_ra0)),
        # RASOF: RACNT=63, MRPTR=0 → overflow with no MemRAS
        _case("legality", "call_iiii_ra", "iiii", word,
              rasof_inp, None,
              "RASOF", None, SC_CALL_RASOF,
              "legality RASOF: ra0=%s (RACNT=63, MRPTR=0); "
              "ra63=[count=1, addr=0xCCCC00000000]; PC+4=0xFFFF00000004 ≠ "
              "ra63[47:0] → C3b: RACNT==63, MRPTR==0 → RASOF (0x8A)"
              % rasof_in_ra0),
        # C3b MemRAS: RACNT=63, MRPTR!=0 → spill oldest to MemRAS
        _case("semantic", "call_iiii_ra", "iiii", word,
              c3b_inp,
              {"ra": {
                  "ra0": c3b_out_ra0,
                  "ra63": c3b_out_ra63,
              },
               "memory": [{
                   "address": c3b_mem_addr,
                   "value": c3b_mem_val,
               }]},
              None, TARGET, SC_CALL_C3b_MEM,
              "semantic C3b (MemRAS spill): ra0=%s (RACNT=63, MRPTR=0x%X); "
              "ra1=[count=5, addr=0xDDDD00000000] (oldest, idx=64-63=1); "
              "ra63=[count=1, addr=0xCCCC00000000]; PC+4=0xFFFF00000004 ≠ "
              "ra63[47:0] → C3b: MRPTR-=8→%s, spill ra1→MemRAS[%s], "
              "push new ra63=[1, 0xFFFF00000004]; RACNT stays 63"
              % (c3b_in_ra0, c3b_mrptr, c3b_mrptr_after, c3b_mem_addr)),
    ]


# ── call-rrii (D7 rewrite) ───────────────────────────────────────────
def _gen_call_rrii():
    op = int(BY_KEY[("call_rrii_ra", "rrii")]["op"], 16)
    enc_word = _build_word_rrii(op, 0, 0, IMM)
    unmapped_word = _build_word_rrii(op, 3, 0, 0)

    # C1: cold RA → push new entry, RACNT=1
    c1_out_ra0 = _ra0(1, 0)
    c1_out_ra63 = RA64_FMT % ((1 << 48) | (RB0 + 4))

    # C2: recursive → count +1
    c2_in_ra0 = _ra0(1, 0)
    c2_in_ra63 = RA64_FMT % ((1 << 48) | (RB0 + 4))
    c2_out_ra63 = RA64_FMT % ((2 << 48) | (RB0 + 4))

    # C3a: shift-push (different address)
    c3a_in_ra0 = _ra0(1, 0)
    c3a_in_ra63 = RA64_FMT % ((1 << 48) | 0xAAAA_0000_0000)
    c3a_out_ra0 = _ra0(2, 0)
    c3a_out_ra63 = RA64_FMT % ((1 << 48) | (RB0 + 4))
    c3a_out_ra62 = RA64_FMT % ((1 << 48) | 0xAAAA_0000_0000)

    return [
        _case("encoding", "call_rrii_ra", "rrii", enc_word, {}, None,
              None, None, SC_CALL,
              "encoding: word matches opcodes.yaml mask/value, rbha=rb0 "
              "(index 0), rdhb=rd0 (index 0), imms12=2"),
        # C1: cold RA
        _case("semantic", "call_rrii_ra", "rrii", enc_word, {},
              {"ra": {"ra0": c1_out_ra0, "ra63": c1_out_ra63}},
              None, TARGET, SC_CALL_C1,
              "semantic C1: rb0=0xFFFF00000000, rd0=0, imms12=2, "
              "Addr=0xFFFF00000008; cold RA (RACNT=0, MRPTR=0); "
              "push: ra63=[count=1, ret_addr=0xFFFF00000004], RACNT→1; "
              "ra0=%s" % c1_out_ra0),
        # C2: recursive → count +1
        _case("semantic", "call_rrii_ra", "rrii", enc_word,
              {"ra": {"ra0": c2_in_ra0, "ra63": c2_in_ra63}},
              {"ra": {"ra63": c2_out_ra63}},
              None, TARGET, SC_CALL_C2,
              "semantic C2 (recursive fold): ra0=%s, ra63 input "
              "[count=1, addr=0xFFFF00000004]; PC+4=0xFFFF00000004 == "
              "ra63[47:0] → count+1: ra63=[count=2, addr=0xFFFF00000004]; "
              "RACNT unchanged (1)" % c2_in_ra0),
        # C3a: shift-push (different address)
        _case("semantic", "call_rrii_ra", "rrii", enc_word,
              {"ra": {"ra0": c3a_in_ra0, "ra63": c3a_in_ra63}},
              {"ra": {
                  "ra0": c3a_out_ra0,
                  "ra63": c3a_out_ra63,
                  "ra62": c3a_out_ra62,
              }},
              None, TARGET, SC_CALL_C3a,
              "semantic C3a (shift-push): ra0=%s, ra63 input "
              "[count=1, addr=0xAAAA00000000]; PC+4=0xFFFF00000004 ≠ "
              "ra63[47:0] → shift-push: new ra63=[1, 0xFFFF00000004], "
              "old ra63→ra62=[1, 0xAAAA00000000]; RACNT→2, ra0=%s"
              % (c3a_in_ra0, c3a_out_ra0)),
        _case("legality", "call_rrii_ra", "rrii", unmapped_word,
              {"rb": {"rb3": "0x0000000000000000"}}, None,
              "UNMAPPED", None, SC_CALL_LEG,
              "legality UNMAPPED: rbha=rb3=0, rdhb=rd0=0, imms12=0 → "
              "addr=0 → unmapped (0x87), ADR-0004 D5.6"),
    ]


# ── ret-riii (D7 rewrite) ────────────────────────────────────────────
def _gen_ret_riii():
    op = int(BY_KEY[("ret_riii_ra", "riii")]["op"], 16)
    word = _build_word_riii(op, 0, 0)  # rdha=rd0, imms18=0

    # D2: RACNT>0, count>1 → decrement count, RACNT unchanged
    #   input: RACNT=2, ra63=[count=3, addr=PC+4]
    #   output: ra63=[count=2, addr=PC+4]; RACNT stays 2
    d2_in_ra0 = _ra0(2, 0)
    d2_in_ra63 = RA64_FMT % ((3 << 48) | (RB0 + 4))
    d2_out_ra63 = RA64_FMT % ((2 << 48) | (RB0 + 4))

    # D3: RACNT>0, count==1 → pop stack top, RACNT -= 1
    #   input: RACNT=2, ra63=[count=1, addr=PC+4], ra62=[count=1, addr=0xAAAA00000000]
    #   output: ra63=[count=1, addr=0xAAAA00000000] (shifted from ra62), RACNT→1
    d3_in_ra0 = _ra0(2, 0)
    d3_in_ra63 = RA64_FMT % ((1 << 48) | (RB0 + 4))
    d3_in_ra62 = RA64_FMT % ((1 << 48) | 0xAAAA_0000_0000)
    d3_out_ra0 = _ra0(1, 0)
    d3_out_ra63 = RA64_FMT % ((1 << 48) | 0xAAAA_0000_0000)

    # D4b cnt>1: RACNT==0, MRPTR!=0, MemRAS entry count>1 → push to stack, RACNT=1
    #   MemRAS entry: count=3, addr=0xBBBB00000000 at MRPTR
    #   After: count-1=2, pushed to ra63, MRPTR+=8, RACNT=1
    #   PC = entry[47:0] = 0xBBBB00000000
    d4b_mrptr = MRPTR_BASE
    d4b_mrptr_after = "0x%012X" % (d4b_mrptr + 8)
    d4b_in_ra0 = _ra0(0, d4b_mrptr)
    d4b_mem_in = RA64_FMT % ((3 << 48) | 0xBBBB_0000_0000)
    d4b_out_ra0 = _ra0(1, d4b_mrptr + 8)
    d4b_out_ra63 = RA64_FMT % ((2 << 48) | 0xBBBB_0000_0000)
    d4b_pc = HEX48_FMT % 0xBBBB_0000_0000  # PC = entry[47:0]

    # D4b cnt=1: RACNT==0, MRPTR!=0, MemRAS entry count=1 → consume, no push
    #   MemRAS entry: count=1, addr=0xCCCC00000000 at MRPTR
    #   After: PC=entry[47:0], MRPTR+=8, RACNT stays 0, no RegRAS change
    d4b1_mrptr = MRPTR_BASE
    d4b1_mrptr_after = "0x%012X" % (d4b1_mrptr + 8)
    d4b1_in_ra0 = _ra0(0, d4b1_mrptr)
    d4b1_mem_in = RA64_FMT % ((1 << 48) | 0xCCCC_0000_0000)
    d4b1_out_ra0 = _ra0(0, d4b1_mrptr + 8)
    d4b1_pc = HEX48_FMT % 0xCCCC_0000_0000  # PC = entry[47:0]

    # D4b cnt=0: RACNT==0, MRPTR!=0, MemRAS entry count=0 → RASUF
    d4b0_in_ra0 = _ra0(0, d4b_mrptr)
    d4b0_mem_in = RA64_FMT % ((0 << 48) | 0xEEEE_0000_0000)

    # D4a: RACNT==0, MRPTR==0 → RASUF
    d4a_in_ra0 = _ra0(0, 0)

    # TESTCASES-022t: ret rd1, 42 → normal pop (mirrors D3) + rd1 = sign_extend(42)
    rd1_in_ra0 = _ra0(2, 0)
    rd1_in_ra63 = RA64_FMT % ((1 << 48) | (RB0 + 4))
    rd1_in_ra62 = RA64_FMT % ((1 << 48) | 0xAAAA_0000_0000)
    rd1_out_ra0 = _ra0(1, 0)
    rd1_out_ra63 = RA64_FMT % ((1 << 48) | 0xAAAA_0000_0000)
    rd1_word = _build_word_riii(op, 1, 42)          # 0x7604002A
    rd1_value = RA64_FMT % 42                       # sign_extend(42) = 0x2A

    return [
        # D2: decrement recursive count
        _case("semantic", "ret_riii_ra", "riii", word,
              {"ra": {"ra0": d2_in_ra0, "ra63": d2_in_ra63}},
              {"ra": {"ra63": d2_out_ra63}},
              None, RETURN_ADDR, SC_RET_D2,
              "semantic D2 (count>1): ra0=%s, ra63=[count=3, "
              "addr=0xFFFF00000004]; ret → PC=ra63[47:0]=0xFFFF00000004; "
              "count 3→2, RACNT unchanged (2); ra63=[count=2, "
              "addr=0xFFFF00000004]" % d2_in_ra0),
        # D3: pop stack top (count==1)
        _case("semantic", "ret_riii_ra", "riii", word,
              {"ra": {"ra0": d3_in_ra0, "ra63": d3_in_ra63,
                       "ra62": d3_in_ra62}},
              {"ra": {"ra0": d3_out_ra0, "ra63": d3_out_ra63}},
              None, RETURN_ADDR, SC_RET_D3,
              "semantic D3 (count=1, pop): ra0=%s, ra63=[count=1, "
              "addr=0xFFFF00000004], ra62=[count=1, addr=0xAAAA00000000]; "
              "ret → PC=0xFFFF00000004; count=1 → pop: shift-down, "
              "ra62→ra63=[count=1, addr=0xAAAA00000000]; RACNT→1, ra0=%s"
              % (d3_in_ra0, d3_out_ra0)),
        # D4b cnt>1: restore from MemRAS, push to stack
        _case("semantic", "ret_riii_ra", "riii", word,
              {"ra": {"ra0": d4b_in_ra0},
               "memory": [{"address": "0x%012X" % d4b_mrptr,
                           "value": d4b_mem_in}]},
              {"ra": {"ra0": d4b_out_ra0, "ra63": d4b_out_ra63}},
              None, d4b_pc, SC_RET_D4b,
              "semantic D4b (MemRAS count>1): ra0=%s (RACNT=0, MRPTR=0x%X); "
              "MemRAS[MRPTR]=[count=3, addr=0xBBBB00000000]; "
              "ret → PC=条目[47:0]=0xBBBB00000000; count>1→push to stack: "
              "ra63=[count=2, addr=0xBBBB00000000], MRPTR+=8→%s, RACNT=1"
              % (d4b_in_ra0, d4b_mrptr, d4b_mrptr_after)),
        # D4b cnt=1: restore from MemRAS, consume (no push)
        _case("semantic", "ret_riii_ra", "riii", word,
              {"ra": {"ra0": d4b1_in_ra0},
               "memory": [{"address": "0x%012X" % d4b1_mrptr,
                           "value": d4b1_mem_in}]},
              {"ra": {"ra0": d4b1_out_ra0}},
              None, d4b1_pc, SC_RET_D4b,
              "semantic D4b (MemRAS count=1): ra0=%s (RACNT=0, MRPTR=0x%X); "
              "MemRAS[MRPTR]=[count=1, addr=0xCCCC00000000]; "
              "ret → PC=条目[47:0]=0xCCCC00000000; count=1→consume: "
              "MRPTR+=8→%s, RACNT stays 0; no RegRAS change"
              % (d4b1_in_ra0, d4b1_mrptr, d4b1_mrptr_after)),
        # D4b cnt=0: MemRAS entry count=0 → RASUF
        _case("legality", "ret_riii_ra", "riii", word,
              {"ra": {"ra0": d4b0_in_ra0},
               "memory": [{"address": "0x%012X" % d4b_mrptr,
                           "value": d4b0_mem_in}]},
              None,
              "RASUF", None, SC_RET_D4B_RASUF,
              "legality D4b RASUF (MemRAS count=0): ra0=%s (RACNT=0, "
              "MRPTR=0x%X); MemRAS[MRPTR]=[count=0, addr=0xEEEE00000000]; "
              "ret → read MemRAS: count=0 → RASUF (0x8B)"
              % (d4b0_in_ra0, d4b_mrptr)),
        # D4a: RACNT==0, MRPTR==0 → RASUF (cold RA)
        _case("legality", "ret_riii_ra", "riii", word,
              {"ra": {"ra0": d4a_in_ra0}}, None,
              "RASUF", None, SC_RET_RASUF,
              "legality D4a RASUF: ra0=%s (RACNT=0, MRPTR=0); "
              "ret → D4: RACNT==0, MRPTR==0 → RASUF (0x8B)" % d4a_in_ra0),
        # ── TESTCASES-022t: ret rd0 ⇒ imms18 MUST be 0 (dst_rd0_nonzero) ──
        # rdha=rd0, imms18=1 (≠0) → ILLI
        _case("legality", "ret_riii_ra", "riii", _build_word_riii(op, 0, 1),
              {}, None,
              "ILLI", None, SC_RET_RD0_IMMS18,
              "legality dst_rd0_nonzero: rdha=rd0, imms18=1 (≠0) → ILLI (0x88); "
              "word=0x76<<24|0<<18|1=0x76000001"),
        # rdha=rd0, imms18=-1 (0x3FFFF, ≠0) → ILLI
        _case("legality", "ret_riii_ra", "riii",
              _build_word_riii(op, 0, -1 & 0x3FFFF),
              {}, None,
              "ILLI", None, SC_RET_RD0_IMMS18,
              "legality dst_rd0_nonzero: rdha=rd0, imms18=-1 (0x3FFFF, ≠0) → "
              "ILLI (0x88); word=0x76<<24|0<<18|0x3FFFF=0x7603FFFF"),
        # rdha=rd1 (≠rd0), imms18=42 → legal; normal pop (mirrors D3) + rd1 write
        _case("semantic", "ret_riii_ra", "riii", rd1_word,
              {"ra": {"ra0": rd1_in_ra0, "ra63": rd1_in_ra63,
                       "ra62": rd1_in_ra62}},
              {"rd": {"rd1": rd1_value},
               "ra": {"ra0": rd1_out_ra0, "ra63": rd1_out_ra63}},
              None, RETURN_ADDR, SC_RET_RD0_IMMS18,
              "semantic ret rd1, 42 (rdha=rd1≠rd0, unconstrained): ra0=%s, "
              "ra63=[count=1, addr=0xFFFF00000004], ra62=[count=1, "
              "addr=0xAAAA00000000]; ret → PC=0xFFFF00000004; count=1 → pop: "
              "ra62→ra63=[count=1, addr=0xAAAA00000000], RACNT→1 (ra0=%s); "
              "rd1 = sign_extend(42) = 0x2A"
              % (rd1_in_ra0, rd1_out_ra0)),
    ]


# ── Write YAML ────────────────────────────────────────────────────────
def _write_yaml(filename, header, cases):
    path = os.path.join(OUT_DIR, filename)
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(path, "w") as f:
        f.write(header)
        yaml.dump(cases, f, default_flow_style=False, allow_unicode=True,
                  width=120)
    n_enc = sum(1 for c in cases if c["class"] == "encoding")
    n_sem = sum(1 for c in cases if c["class"] == "semantic")
    n_leg = sum(1 for c in cases if c["class"] == "legality")
    print("Wrote %s: %d cases (%d encoding, %d semantic, %d legality)" % (
        path, len(cases), n_enc, n_sem, n_leg))


# ── Main ──────────────────────────────────────────────────────────────
def main():
    jump_cases = _gen_jump_iiii() + _gen_jump_rrii()
    call_cases = _gen_call_iiii() + _gen_call_rrii()
    ret_cases = _gen_ret_riii()

    _write_yaml("ctrl-jump.yaml", HEADER_JUMP, jump_cases)
    _write_yaml("ctrl-call.yaml", HEADER_CALL, call_cases)
    _write_yaml("ctrl-ret.yaml", HEADER_RET, ret_cases)

    total = len(jump_cases) + len(call_cases) + len(ret_cases)
    print("\nTotal: %d cases across 3 files" % total)
    print("Identities covered: jump-iiii, jump-rrii, call-iiii, call-rrii, ret-riii")
    return 0


if __name__ == "__main__":
    sys.exit(main())
