; ======================================================================
; GENERATED by tools/testcases/generate_lit_vectors.py — DO NOT EDIT
; lit MC 编码正例
; 期望编码机械派生自 contracts/opcodes.yaml（op/value/mask/fields）；
; 无 llvm-mc/llc/QEMU 反填。重跑: python3 tools/testcases/generate_lit_vectors.py
; source: contracts/opcodes.yaml
; RUN: %llvm_mc --triple=dadao-unknown-elf -filetype=obj %s -o %t
; RUN: %llvm_objdump -d --triple=dadao-unknown-elf %t | %FileCheck %s --check-prefix=OBJ
; RUN: %llvm_mc --triple=dadao-unknown-elf -filetype=asm %s | %FileCheck %s --check-prefix=ASM
; ======================================================================

.text

; @src escape_ciii_cfx 7efc0002 | SimRISC-00 §SimRISC QFC
; OBJ: {{[0-9a-f]+:}} 7e fc 00 02{{.*}}escape
; ASM: escape cfx63, [excp_cause_ip, 8]
escape cfx63, [excp_cause_ip, 8]

; @src trap_ciii_cfx 7ffc0001 | SimRISC-00 §SimRISC QFC
; OBJ: {{[0-9a-f]+:}} 7f fc 00 01{{.*}}trap
; ASM: trap cfx63, 1
trap cfx63, 1

; @src cfx2rc_crrr_cfx 7bfc8048 | SimRISC-00 §SimRISC QFC
; OBJ: {{[0-9a-f]+:}} 7b fc 80 48{{.*}}cfx2rc
; ASM: cfx2rc cfx63, cg8, rc1, rd8
cfx2rc cfx63, cg8, rc1, rd8

; @src call_iiii_ra 74000003 | SimRISC-06 §函数调用
; OBJ: {{[0-9a-f]+:}} 74 00 00 03{{.*}}call
; ASM: call [rb0, 12]
call [rb0, 12]

; @src fence_oiii_imm 77000000 | SimRISC-12 §fence指令
; OBJ: {{[0-9a-f]+:}} 77 00 00 00{{.*}}fence
; ASM: fence 0
fence 0

; @src swym_oiii_imm 77880008 | SimRISC-11 §占位指令
; OBJ: {{[0-9a-f]+:}} 77 88 00 08{{.*}}swym
; ASM: swym 8
swym 8

; @src ext.so_orri_rd 40648241 | SimRISC-04 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 40 64 82 41{{.*}}ext.so
; ASM: ext.so rd8, rd9, 1
ext.so rd8, rd9, 1

; @src fo2fo_orri_rf 44288241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 28 82 41{{.*}}fo2fo
; ASM: fo2fo {rf8}, {rf9}
fo2fo {rf8}, {rf9}

; @src foroot_orri_rf 44388242 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 38 82 42{{.*}}foroot
; ASM: foroot rf8, rf9, 2
foroot rf8, rf9, 2

; @src add.o_orrr_bbd 40c0824a | SimRISC-05 §加减操作
; OBJ: {{[0-9a-f]+:}} 40 c0 82 4a{{.*}}add.o
; ASM: add.o rb8, rb9, rd10
add.o rb8, rb9, rd10

; @src add.si_riii_rb 5b200008 | SimRISC-05 §自增自减
; OBJ: {{[0-9a-f]+:}} 5b 20 00 08{{.*}}add.si
; ASM: add.si rb8, 8
add.si rb8, 8

; @src br.n_riii_rd 68200003 | SimRISC-06 §条件跳转指令
; OBJ: {{[0-9a-f]+:}} 68 20 00 03{{.*}}br.n
; ASM: br.n {rd8}?, [rb0, 12]
br.n {rd8}?, [rb0, 12]

; @src ret_riii_ra 76200008 | SimRISC-06 §函数返回
; OBJ: {{[0-9a-f]+:}} 76 20 00 08{{.*}}ret
; ASM: ret rd8, 8
ret rd8, 8

; @src br.eq_rrii_rd 6e209004 | SimRISC-06 §条件跳转指令
; OBJ: {{[0-9a-f]+:}} 6e 20 90 04{{.*}}br.eq
; ASM: br.eq {rd8, rd9}?, [rb0, 16]
br.eq {rd8, rd9}?, [rb0, 16]

; @src call_rrii_ra 75209018 | SimRISC-06 §函数调用
; OBJ: {{[0-9a-f]+:}} 75 20 90 18{{.*}}call
; ASM: call [rb8, rd9, 96]
call [rb8, rd9, 96]

; @src cmp.si_rrii_rd 5d209001 | SimRISC-04 §比较操作
; OBJ: {{[0-9a-f]+:}} 5d 20 90 01{{.*}}cmp.si
; ASM: cmp.si rd8, rd9, 1
cmp.si rd8, rd9, 1

; @src ld.o_rrii_ra 24209008 | SimRISC-01 §存取RA寄存器
; OBJ: {{[0-9a-f]+:}} 24 20 90 08{{.*}}ld.o
; ASM: ld.o ra8, [rb9, 8]
ld.o ra8, [rb9, 8]

; @src ldm.o_rrri_ra 3c200241 | SimRISC-01 §存取RA寄存器
; OBJ: {{[0-9a-f]+:}} 3c 20 02 41{{.*}}ldm.o
; ASM: ldm.o {ra8}, [rb0, rd9]
ldm.o {ra8}, [rb0, rd9]

; @src add.so_rrrr_rd 5120928b | SimRISC-04 §加减操作
; OBJ: {{[0-9a-f]+:}} 51 20 92 8b{{.*}}add.so
; ASM: add.so {rd8, rd9}, rd10, rd11
add.so {rd8, rd9}, rd10, rd11

; @src cs.eq_rrrr_rd 6620928b | SimRISC-02 §条件赋值：Conditional Assignment
; OBJ: {{[0-9a-f]+:}} 66 20 92 8b{{.*}}cs.eq
; ASM: cs.eq {rd8, rd9}?, rd10, rd11
cs.eq {rd8, rd9}?, rd10, rd11

; @src cs.n_rrrr_rd 6020928b | SimRISC-02 §条件赋值：Conditional Assignment
; OBJ: {{[0-9a-f]+:}} 60 20 92 8b{{.*}}cs.n
; ASM: cs.n {rd8}?, rd9, rd10, rd11
cs.n {rd8}?, rd9, rd10, rd11

; @src andn.w_rwii_rb 4b211234 | SimRISC-03 §立即数常数赋值：Immediate constant
; OBJ: {{[0-9a-f]+:}} 4b 21 12 34{{.*}}andn.w
; ASM: andn.w rb8, wp1, 0x1234
andn.w rb8, wp1, 0x1234
