; ======================================================================
; GENERATED by tools/testcases/generate_lit_vectors.py — DO NOT EDIT
; lit MC 编码正例
; 期望编码机械派生自 contracts/opcodes.yaml（op/value/mask/fields）；
; 无 llvm-mc/llc/QEMU 反填。重跑: python3 tools/testcases/generate_lit_vectors.py
; source: contracts/opcodes.yaml
; RUN: %llvm_mc --triple=dadao-unknown-elf -filetype=obj %s -o %t
; RUN: %llvm_objdump -d --triple=dadao-unknown-elf %t | %FileCheck %s --check-prefix=OBJ
; RUN: %llvm_mc --triple=dadao-unknown-elf -filetype=asm %s | %FileCheck %s --check-prefix=ASM
; ======================================================================

.text

; @src add.si_riii_rb 5b200008 | SimRISC-05 §自增自减
; OBJ: {{[0-9a-f]+:}} 5b 20 00 08{{.*}}add.si
; ASM: add.si rb8, 8
add.si rb8, 8

; @src add.si_riii_rd 59200008 | SimRISC-04 §自增自减
; OBJ: {{[0-9a-f]+:}} 59 20 00 08{{.*}}add.si
; ASM: add.si rd8, 8
add.si rd8, 8

; @src br.n_riii_rd 68200003 | SimRISC-06 §条件跳转指令
; OBJ: {{[0-9a-f]+:}} 68 20 00 03{{.*}}br.n
; ASM: br.n {rd8}?, [rb0, 12]
br.n {rd8}?, [rb0, 12]

; @src br.nn_riii_rd 69200003 | SimRISC-06 §条件跳转指令
; OBJ: {{[0-9a-f]+:}} 69 20 00 03{{.*}}br.nn
; ASM: br.nn {rd8}?, [rb0, 12]
br.nn {rd8}?, [rb0, 12]

; @src br.np_riii_rd 6d200003 | SimRISC-06 §条件跳转指令
; OBJ: {{[0-9a-f]+:}} 6d 20 00 03{{.*}}br.np
; ASM: br.np {rd8}?, [rb0, 12]
br.np {rd8}?, [rb0, 12]

; @src br.nz_riii_rb 73200003 | SimRISC-06 §条件跳转指令
; OBJ: {{[0-9a-f]+:}} 73 20 00 03{{.*}}br.nz
; ASM: br.nz {rb8}?, [rb0, 12]
br.nz {rb8}?, [rb0, 12]

; @src br.nz_riii_rd 6b200003 | SimRISC-06 §条件跳转指令
; OBJ: {{[0-9a-f]+:}} 6b 20 00 03{{.*}}br.nz
; ASM: br.nz {rd8}?, [rb0, 12]
br.nz {rd8}?, [rb0, 12]

; @src br.p_riii_rd 6c200003 | SimRISC-06 §条件跳转指令
; OBJ: {{[0-9a-f]+:}} 6c 20 00 03{{.*}}br.p
; ASM: br.p {rd8}?, [rb0, 12]
br.p {rd8}?, [rb0, 12]

; @src br.z_riii_rb 72200003 | SimRISC-06 §条件跳转指令
; OBJ: {{[0-9a-f]+:}} 72 20 00 03{{.*}}br.z
; ASM: br.z {rb8}?, [rb0, 12]
br.z {rb8}?, [rb0, 12]

; @src br.z_riii_rd 6a200003 | SimRISC-06 §条件跳转指令
; OBJ: {{[0-9a-f]+:}} 6a 20 00 03{{.*}}br.z
; ASM: br.z {rd8}?, [rb0, 12]
br.z {rd8}?, [rb0, 12]

; @src ret_riii_ra 76200008 | SimRISC-06 §函数返回
; OBJ: {{[0-9a-f]+:}} 76 20 00 08{{.*}}ret
; ASM: ret rd8, 8
ret rd8, 8
