; ======================================================================
; GENERATED by tools/testcases/generate_lit_vectors.py — DO NOT EDIT
; lit MC 编码正例
; 期望编码机械派生自 contracts/opcodes.yaml（op/value/mask/fields）；
; 无 llvm-mc/llc/QEMU 反填。重跑: python3 tools/testcases/generate_lit_vectors.py
; source: contracts/opcodes.yaml
; RUN: %llvm_mc --triple=dadao-unknown-elf -filetype=obj %s -o %t
; RUN: %llvm_objdump -d --triple=dadao-unknown-elf %t | %FileCheck %s --check-prefix=OBJ
; RUN: %llvm_mc --triple=dadao-unknown-elf -filetype=asm %s | %FileCheck %s --check-prefix=ASM
; ======================================================================

.text

; @src ext.so_orri_rd 40648241 | SimRISC-04 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 40 64 82 41{{.*}}ext.so
; ASM: ext.so rd8, rd9, 1
ext.so rd8, rd9, 1

; @src ext.uo_orri_rd 40608241 | SimRISC-04 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 40 60 82 41{{.*}}ext.uo
; ASM: ext.uo rd8, rd9, 1
ext.uo rd8, rd9, 1

; @src fo2fo_orri_rf 44288241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 28 82 41{{.*}}fo2fo
; ASM: fo2fo {rf8}, {rf9}
fo2fo {rf8}, {rf9}

; @src fo2ft_orri_rf 44248241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 24 82 41{{.*}}fo2ft
; ASM: fo2ft {rf8}, {rf9}
fo2ft {rf8}, {rf9}

; @src fo2io_orri_rf 44e48241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 e4 82 41{{.*}}fo2io
; ASM: fo2io {rd8}, {rf9}
fo2io {rd8}, {rf9}

; @src fo2it_orri_rf 44e08241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 e0 82 41{{.*}}fo2it
; ASM: fo2it {rd8}, {rf9}
fo2it {rd8}, {rf9}

; @src fo2uo_orri_rf 44ec8241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 ec 82 41{{.*}}fo2uo
; ASM: fo2uo {rd8}, {rf9}
fo2uo {rd8}, {rf9}

; @src fo2ut_orri_rf 44e88241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 e8 82 41{{.*}}fo2ut
; ASM: fo2ut {rd8}, {rf9}
fo2ut {rd8}, {rf9}

; @src focls_orri_rf 44208241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 20 82 41{{.*}}focls
; ASM: focls {rd8}, {rf9}
focls {rd8}, {rf9}

; @src foroot_orri_rf 44388242 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 38 82 42{{.*}}foroot
; ASM: foroot rf8, rf9, 2
foroot rf8, rf9, 2

; @src ft2fo_orri_rf 44048241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 04 82 41{{.*}}ft2fo
; ASM: ft2fo {rf8}, {rf9}
ft2fo {rf8}, {rf9}

; @src ft2ft_orri_rf 44088241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 08 82 41{{.*}}ft2ft
; ASM: ft2ft {rf8}, {rf9}
ft2ft {rf8}, {rf9}

; @src ft2io_orri_rf 44c48241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 c4 82 41{{.*}}ft2io
; ASM: ft2io {rd8}, {rf9}
ft2io {rd8}, {rf9}

; @src ft2it_orri_rf 44c08241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 c0 82 41{{.*}}ft2it
; ASM: ft2it {rd8}, {rf9}
ft2it {rd8}, {rf9}

; @src ft2uo_orri_rf 44cc8241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 cc 82 41{{.*}}ft2uo
; ASM: ft2uo {rd8}, {rf9}
ft2uo {rd8}, {rf9}

; @src ft2ut_orri_rf 44c88241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 c8 82 41{{.*}}ft2ut
; ASM: ft2ut {rd8}, {rf9}
ft2ut {rd8}, {rf9}

; @src ftcls_orri_rf 44008241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 00 82 41{{.*}}ftcls
; ASM: ftcls {rd8}, {rf9}
ftcls {rd8}, {rf9}

; @src ftroot_orri_rf 44188242 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 18 82 42{{.*}}ftroot
; ASM: ftroot rf8, rf9, 2
ftroot rf8, rf9, 2

; @src io2fo_orri_rf 44f48241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 f4 82 41{{.*}}io2fo
; ASM: io2fo {rf8}, {rd9}
io2fo {rf8}, {rd9}

; @src io2ft_orri_rf 44d48241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 d4 82 41{{.*}}io2ft
; ASM: io2ft {rf8}, {rd9}
io2ft {rf8}, {rd9}

; @src it2fo_orri_rf 44f08241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 f0 82 41{{.*}}it2fo
; ASM: it2fo {rf8}, {rd9}
it2fo {rf8}, {rd9}

; @src it2ft_orri_rf 44d08241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 d0 82 41{{.*}}it2ft
; ASM: it2ft {rf8}, {rd9}
it2ft {rf8}, {rd9}

; @src ra2rd_orri_ra 40b88241 | SimRISC-02 §寄存器组之间块赋值
; OBJ: {{[0-9a-f]+:}} 40 b8 82 41{{.*}}ra2rd
; ASM: ra2rd {rd8}, {ra9}
ra2rd {rd8}, {ra9}

; @src rb2rb_orri_rb 40d08241 | SimRISC-02 §寄存器组之间块赋值
; OBJ: {{[0-9a-f]+:}} 40 d0 82 41{{.*}}rb2rb
; ASM: rb2rb {rb8}, {rb9}
rb2rb {rb8}, {rb9}

; @src rb2rd_orri_rb 40d88241 | SimRISC-02 §寄存器组之间块赋值
; OBJ: {{[0-9a-f]+:}} 40 d8 82 41{{.*}}rb2rd
; ASM: rb2rd {rd8}, {rb9}
rb2rd {rd8}, {rb9}

; @src rd2ra_orri_ra 40b48241 | SimRISC-02 §寄存器组之间块赋值
; OBJ: {{[0-9a-f]+:}} 40 b4 82 41{{.*}}rd2ra
; ASM: rd2ra {ra8}, {rd9}
rd2ra {ra8}, {rd9}

; @src rd2rb_orri_rb 40d48241 | SimRISC-02 §寄存器组之间块赋值
; OBJ: {{[0-9a-f]+:}} 40 d4 82 41{{.*}}rd2rb
; ASM: rd2rb {rb8}, {rd9}
rd2rb {rb8}, {rd9}

; @src rd2rd_orri_rd 40b08241 | SimRISC-02 §寄存器组之间块赋值
; OBJ: {{[0-9a-f]+:}} 40 b0 82 41{{.*}}rd2rd
; ASM: rd2rd {rd8}, {rd9}
rd2rd {rd8}, {rd9}

; @src rd2rf_orri_rf 40f48241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 40 f4 82 41{{.*}}rd2rf
; ASM: rd2rf {rf8}, {rd9}
rd2rf {rf8}, {rd9}

; @src rf2rd_orri_rf 40f88241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 40 f8 82 41{{.*}}rf2rd
; ASM: rf2rd {rd8}, {rf9}
rf2rd {rd8}, {rf9}

; @src shl.ub_orri_rd 43708241 | SimRISC-10 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 43 70 82 41{{.*}}shl.ub
; ASM: shl.ub rd8, rd9, 1
shl.ub rd8, rd9, 1

; @src shl.uo_orri_rd 40708241 | SimRISC-04 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 40 70 82 41{{.*}}shl.uo
; ASM: shl.uo rd8, rd9, 1
shl.uo rd8, rd9, 1

; @src shl.ut_orri_rd 41708241 | SimRISC-08 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 41 70 82 41{{.*}}shl.ut
; ASM: shl.ut rd8, rd9, 1
shl.ut rd8, rd9, 1

; @src shl.uw_orri_rd 42708241 | SimRISC-09 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 42 70 82 41{{.*}}shl.uw
; ASM: shl.uw rd8, rd9, 1
shl.uw rd8, rd9, 1

; @src shr.sb_orri_rd 436c8241 | SimRISC-10 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 43 6c 82 41{{.*}}shr.sb
; ASM: shr.sb rd8, rd9, 1
shr.sb rd8, rd9, 1

; @src shr.so_orri_rd 406c8241 | SimRISC-04 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 40 6c 82 41{{.*}}shr.so
; ASM: shr.so rd8, rd9, 1
shr.so rd8, rd9, 1

; @src shr.st_orri_rd 416c8241 | SimRISC-08 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 41 6c 82 41{{.*}}shr.st
; ASM: shr.st rd8, rd9, 1
shr.st rd8, rd9, 1

; @src shr.sw_orri_rd 426c8241 | SimRISC-09 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 42 6c 82 41{{.*}}shr.sw
; ASM: shr.sw rd8, rd9, 1
shr.sw rd8, rd9, 1

; @src shr.ub_orri_rd 43688241 | SimRISC-10 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 43 68 82 41{{.*}}shr.ub
; ASM: shr.ub rd8, rd9, 1
shr.ub rd8, rd9, 1

; @src shr.uo_orri_rd 40688241 | SimRISC-04 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 40 68 82 41{{.*}}shr.uo
; ASM: shr.uo rd8, rd9, 1
shr.uo rd8, rd9, 1

; @src shr.ut_orri_rd 41688241 | SimRISC-08 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 41 68 82 41{{.*}}shr.ut
; ASM: shr.ut rd8, rd9, 1
shr.ut rd8, rd9, 1

; @src shr.uw_orri_rd 42688241 | SimRISC-09 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 42 68 82 41{{.*}}shr.uw
; ASM: shr.uw rd8, rd9, 1
shr.uw rd8, rd9, 1

; @src uo2fo_orri_rf 44fc8241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 fc 82 41{{.*}}uo2fo
; ASM: uo2fo {rf8}, {rd9}
uo2fo {rf8}, {rd9}

; @src uo2ft_orri_rf 44dc8241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 dc 82 41{{.*}}uo2ft
; ASM: uo2ft {rf8}, {rd9}
uo2ft {rf8}, {rd9}

; @src ut2fo_orri_rf 44f88241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 f8 82 41{{.*}}ut2fo
; ASM: ut2fo {rf8}, {rd9}
ut2fo {rf8}, {rd9}

; @src ut2ft_orri_rf 44d88241 | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 d8 82 41{{.*}}ut2ft
; ASM: ut2ft {rf8}, {rd9}
ut2ft {rf8}, {rd9}
