; ======================================================================
; GENERATED by tools/testcases/generate_lit_vectors.py — DO NOT EDIT
; lit MC 编码正例
; 期望编码机械派生自 contracts/opcodes.yaml（op/value/mask/fields）；
; 无 llvm-mc/llc/QEMU 反填。重跑: python3 tools/testcases/generate_lit_vectors.py
; source: contracts/opcodes.yaml
; RUN: %llvm_mc --triple=dadao-unknown-elf -filetype=obj %s -o %t
; RUN: %llvm_objdump -d --triple=dadao-unknown-elf %t | %FileCheck %s --check-prefix=OBJ
; RUN: %llvm_mc --triple=dadao-unknown-elf -filetype=asm %s | %FileCheck %s --check-prefix=ASM
; ======================================================================

.text

; @src add.o_orrr_bbd 40c0824a | SimRISC-05 §加减操作
; OBJ: {{[0-9a-f]+:}} 40 c0 82 4a{{.*}}add.o
; ASM: add.o rb8, rb9, rd10
add.o rb8, rb9, rd10

; @src add.sb_orrr_rd 4384824a | SimRISC-10 §加减操作
; OBJ: {{[0-9a-f]+:}} 43 84 82 4a{{.*}}add.sb
; ASM: add.sb rd8, rd9, rd10
add.sb rd8, rd9, rd10

; @src add.st_orrr_rd 4184824a | SimRISC-08 §加减操作
; OBJ: {{[0-9a-f]+:}} 41 84 82 4a{{.*}}add.st
; ASM: add.st rd8, rd9, rd10
add.st rd8, rd9, rd10

; @src add.sw_orrr_rd 4284824a | SimRISC-09 §加减操作
; OBJ: {{[0-9a-f]+:}} 42 84 82 4a{{.*}}add.sw
; ASM: add.sw rd8, rd9, rd10
add.sw rd8, rd9, rd10

; @src add.ub_orrr_rd 4380824a | SimRISC-10 §加减操作
; OBJ: {{[0-9a-f]+:}} 43 80 82 4a{{.*}}add.ub
; ASM: add.ub rd8, rd9, rd10
add.ub rd8, rd9, rd10

; @src add.ut_orrr_rd 4180824a | SimRISC-08 §加减操作
; OBJ: {{[0-9a-f]+:}} 41 80 82 4a{{.*}}add.ut
; ASM: add.ut rd8, rd9, rd10
add.ut rd8, rd9, rd10

; @src add.uw_orrr_rd 4280824a | SimRISC-09 §加减操作
; OBJ: {{[0-9a-f]+:}} 42 80 82 4a{{.*}}add.uw
; ASM: add.uw rd8, rd9, rd10
add.uw rd8, rd9, rd10

; @src and.o_orrr_rd 4020824a | SimRISC-04 §Logic operators：逻辑运算
; OBJ: {{[0-9a-f]+:}} 40 20 82 4a{{.*}}and.o
; ASM: and.o rd8, rd9, rd10
and.o rd8, rd9, rd10

; @src cmp.sb_orrr_rd 43ac824a | SimRISC-10 §比较操作
; OBJ: {{[0-9a-f]+:}} 43 ac 82 4a{{.*}}cmp.sb
; ASM: cmp.sb rd8, rd9, rd10
cmp.sb rd8, rd9, rd10

; @src cmp.so_orrr_rd 40ac824a | SimRISC-04 §比较操作
; OBJ: {{[0-9a-f]+:}} 40 ac 82 4a{{.*}}cmp.so
; ASM: cmp.so rd8, rd9, rd10
cmp.so rd8, rd9, rd10

; @src cmp.st_orrr_rd 41ac824a | SimRISC-08 §比较操作
; OBJ: {{[0-9a-f]+:}} 41 ac 82 4a{{.*}}cmp.st
; ASM: cmp.st rd8, rd9, rd10
cmp.st rd8, rd9, rd10

; @src cmp.sw_orrr_rd 42ac824a | SimRISC-09 §比较操作
; OBJ: {{[0-9a-f]+:}} 42 ac 82 4a{{.*}}cmp.sw
; ASM: cmp.sw rd8, rd9, rd10
cmp.sw rd8, rd9, rd10

; @src cmp.ub_orrr_rd 43a8824a | SimRISC-10 §比较操作
; OBJ: {{[0-9a-f]+:}} 43 a8 82 4a{{.*}}cmp.ub
; ASM: cmp.ub rd8, rd9, rd10
cmp.ub rd8, rd9, rd10

; @src cmp.uo_orrr_dbb 40c8824a | SimRISC-05 §比较操作
; OBJ: {{[0-9a-f]+:}} 40 c8 82 4a{{.*}}cmp.uo
; ASM: cmp.uo rd8, rb9, rb10
cmp.uo rd8, rb9, rb10

; @src cmp.uo_orrr_rd 40a8824a | SimRISC-04 §比较操作
; OBJ: {{[0-9a-f]+:}} 40 a8 82 4a{{.*}}cmp.uo
; ASM: cmp.uo rd8, rd9, rd10
cmp.uo rd8, rd9, rd10

; @src cmp.ut_orrr_rd 41a8824a | SimRISC-08 §比较操作
; OBJ: {{[0-9a-f]+:}} 41 a8 82 4a{{.*}}cmp.ut
; ASM: cmp.ut rd8, rd9, rd10
cmp.ut rd8, rd9, rd10

; @src cmp.uw_orrr_rd 42a8824a | SimRISC-09 §比较操作
; OBJ: {{[0-9a-f]+:}} 42 a8 82 4a{{.*}}cmp.uw
; ASM: cmp.uw rd8, rd9, rd10
cmp.uw rd8, rd9, rd10

; @src div.sb_orrr_rd 43e4824a | SimRISC-10 §乘除操作
; OBJ: {{[0-9a-f]+:}} 43 e4 82 4a{{.*}}div.sb
; ASM: div.sb rd8, rd9, rd10
div.sb rd8, rd9, rd10

; @src div.so_orrr_rd 40e4824a | SimRISC-04 §乘除操作
; OBJ: {{[0-9a-f]+:}} 40 e4 82 4a{{.*}}div.so
; ASM: div.so rd8, rd9, rd10
div.so rd8, rd9, rd10

; @src div.st_orrr_rd 41e4824a | SimRISC-08 §乘除操作
; OBJ: {{[0-9a-f]+:}} 41 e4 82 4a{{.*}}div.st
; ASM: div.st rd8, rd9, rd10
div.st rd8, rd9, rd10

; @src div.sw_orrr_rd 42e4824a | SimRISC-09 §乘除操作
; OBJ: {{[0-9a-f]+:}} 42 e4 82 4a{{.*}}div.sw
; ASM: div.sw rd8, rd9, rd10
div.sw rd8, rd9, rd10

; @src div.ub_orrr_rd 43e0824a | SimRISC-10 §乘除操作
; OBJ: {{[0-9a-f]+:}} 43 e0 82 4a{{.*}}div.ub
; ASM: div.ub rd8, rd9, rd10
div.ub rd8, rd9, rd10

; @src div.uo_orrr_rd 40e0824a | SimRISC-04 §乘除操作
; OBJ: {{[0-9a-f]+:}} 40 e0 82 4a{{.*}}div.uo
; ASM: div.uo rd8, rd9, rd10
div.uo rd8, rd9, rd10

; @src div.ut_orrr_rd 41e0824a | SimRISC-08 §乘除操作
; OBJ: {{[0-9a-f]+:}} 41 e0 82 4a{{.*}}div.ut
; ASM: div.ut rd8, rd9, rd10
div.ut rd8, rd9, rd10

; @src div.uw_orrr_rd 42e0824a | SimRISC-09 §乘除操作
; OBJ: {{[0-9a-f]+:}} 42 e0 82 4a{{.*}}div.uw
; ASM: div.uw rd8, rd9, rd10
div.uw rd8, rd9, rd10

; @src ext.so_orrr_rd 4044824a | SimRISC-04 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 40 44 82 4a{{.*}}ext.so
; ASM: ext.so rd8, rd9, rd10
ext.so rd8, rd9, rd10

; @src ext.uo_orrr_rd 4040824a | SimRISC-04 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 40 40 82 4a{{.*}}ext.uo
; ASM: ext.uo rd8, rd9, rd10
ext.uo rd8, rd9, rd10

; @src foadd_orrr_rf 4460824a | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 60 82 4a{{.*}}foadd
; ASM: foadd rf8, rf9, rf10
foadd rf8, rf9, rf10

; @src fodiv_orrr_rf 446c824a | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 6c 82 4a{{.*}}fodiv
; ASM: fodiv rf8, rf9, rf10
fodiv rf8, rf9, rf10

; @src fomul_orrr_rf 4468824a | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 68 82 4a{{.*}}fomul
; ASM: fomul rf8, rf9, rf10
fomul rf8, rf9, rf10

; @src foqcmp_orrr_rf 44a0824a | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 a0 82 4a{{.*}}foqcmp
; ASM: foqcmp rd8, rf9, rf10
foqcmp rd8, rf9, rf10

; @src forem_orrr_rf 4470824a | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 70 82 4a{{.*}}forem
; ASM: forem rf8, rf9, rf10
forem rf8, rf9, rf10

; @src fosclb_orrr_rf 4474824a | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 74 82 4a{{.*}}fosclb
; ASM: fosclb rf8, rf9, rf10
fosclb rf8, rf9, rf10

; @src foscmp_orrr_rf 44a4824a | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 a4 82 4a{{.*}}foscmp
; ASM: foscmp rd8, rf9, rf10
foscmp rd8, rf9, rf10

; @src fosgnj_orrr_rf 447c824a | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 7c 82 4a{{.*}}fosgnj
; ASM: fosgnj rf8, rf9, rf10
fosgnj rf8, rf9, rf10

; @src fosgnn_orrr_rf 4478824a | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 78 82 4a{{.*}}fosgnn
; ASM: fosgnn rf8, rf9, rf10
fosgnn rf8, rf9, rf10

; @src fosub_orrr_rf 4464824a | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 64 82 4a{{.*}}fosub
; ASM: fosub rf8, rf9, rf10
fosub rf8, rf9, rf10

; @src ftadd_orrr_rf 4440824a | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 40 82 4a{{.*}}ftadd
; ASM: ftadd rf8, rf9, rf10
ftadd rf8, rf9, rf10

; @src ftdiv_orrr_rf 444c824a | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 4c 82 4a{{.*}}ftdiv
; ASM: ftdiv rf8, rf9, rf10
ftdiv rf8, rf9, rf10

; @src ftmul_orrr_rf 4448824a | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 48 82 4a{{.*}}ftmul
; ASM: ftmul rf8, rf9, rf10
ftmul rf8, rf9, rf10

; @src ftqcmp_orrr_rf 4480824a | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 80 82 4a{{.*}}ftqcmp
; ASM: ftqcmp rd8, rf9, rf10
ftqcmp rd8, rf9, rf10

; @src ftrem_orrr_rf 4450824a | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 50 82 4a{{.*}}ftrem
; ASM: ftrem rf8, rf9, rf10
ftrem rf8, rf9, rf10

; @src ftsclb_orrr_rf 4454824a | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 54 82 4a{{.*}}ftsclb
; ASM: ftsclb rf8, rf9, rf10
ftsclb rf8, rf9, rf10

; @src ftscmp_orrr_rf 4484824a | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 84 82 4a{{.*}}ftscmp
; ASM: ftscmp rd8, rf9, rf10
ftscmp rd8, rf9, rf10

; @src ftsgnj_orrr_rf 445c824a | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 5c 82 4a{{.*}}ftsgnj
; ASM: ftsgnj rf8, rf9, rf10
ftsgnj rf8, rf9, rf10

; @src ftsgnn_orrr_rf 4458824a | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 58 82 4a{{.*}}ftsgnn
; ASM: ftsgnn rf8, rf9, rf10
ftsgnn rf8, rf9, rf10

; @src ftsub_orrr_rf 4444824a | SimRISC-00 §MISC-RF指令编码
; OBJ: {{[0-9a-f]+:}} 44 44 82 4a{{.*}}ftsub
; ASM: ftsub rf8, rf9, rf10
ftsub rf8, rf9, rf10

; @src mul.sb_orrr_rd 43c4824a | SimRISC-10 §乘除操作
; OBJ: {{[0-9a-f]+:}} 43 c4 82 4a{{.*}}mul.sb
; ASM: mul.sb rd8, rd9, rd10
mul.sb rd8, rd9, rd10

; @src mul.st_orrr_rd 41c4824a | SimRISC-08 §乘除操作
; OBJ: {{[0-9a-f]+:}} 41 c4 82 4a{{.*}}mul.st
; ASM: mul.st rd8, rd9, rd10
mul.st rd8, rd9, rd10

; @src mul.sw_orrr_rd 42c4824a | SimRISC-09 §乘除操作
; OBJ: {{[0-9a-f]+:}} 42 c4 82 4a{{.*}}mul.sw
; ASM: mul.sw rd8, rd9, rd10
mul.sw rd8, rd9, rd10

; @src mul.ub_orrr_rd 43c0824a | SimRISC-10 §乘除操作
; OBJ: {{[0-9a-f]+:}} 43 c0 82 4a{{.*}}mul.ub
; ASM: mul.ub rd8, rd9, rd10
mul.ub rd8, rd9, rd10

; @src mul.ut_orrr_rd 41c0824a | SimRISC-08 §乘除操作
; OBJ: {{[0-9a-f]+:}} 41 c0 82 4a{{.*}}mul.ut
; ASM: mul.ut rd8, rd9, rd10
mul.ut rd8, rd9, rd10

; @src mul.uw_orrr_rd 42c0824a | SimRISC-09 §乘除操作
; OBJ: {{[0-9a-f]+:}} 42 c0 82 4a{{.*}}mul.uw
; ASM: mul.uw rd8, rd9, rd10
mul.uw rd8, rd9, rd10

; @src or.o_orrr_rd 4024824a | SimRISC-04 §Logic operators：逻辑运算
; OBJ: {{[0-9a-f]+:}} 40 24 82 4a{{.*}}or.o
; ASM: or.o rd8, rd9, rd10
or.o rd8, rd9, rd10

; @src rem.sb_orrr_rd 43ec824a | SimRISC-10 §乘除操作
; OBJ: {{[0-9a-f]+:}} 43 ec 82 4a{{.*}}rem.sb
; ASM: rem.sb rd8, rd9, rd10
rem.sb rd8, rd9, rd10

; @src rem.so_orrr_rd 40ec824a | SimRISC-04 §乘除操作
; OBJ: {{[0-9a-f]+:}} 40 ec 82 4a{{.*}}rem.so
; ASM: rem.so rd8, rd9, rd10
rem.so rd8, rd9, rd10

; @src rem.st_orrr_rd 41ec824a | SimRISC-08 §乘除操作
; OBJ: {{[0-9a-f]+:}} 41 ec 82 4a{{.*}}rem.st
; ASM: rem.st rd8, rd9, rd10
rem.st rd8, rd9, rd10

; @src rem.sw_orrr_rd 42ec824a | SimRISC-09 §乘除操作
; OBJ: {{[0-9a-f]+:}} 42 ec 82 4a{{.*}}rem.sw
; ASM: rem.sw rd8, rd9, rd10
rem.sw rd8, rd9, rd10

; @src rem.ub_orrr_rd 43e8824a | SimRISC-10 §乘除操作
; OBJ: {{[0-9a-f]+:}} 43 e8 82 4a{{.*}}rem.ub
; ASM: rem.ub rd8, rd9, rd10
rem.ub rd8, rd9, rd10

; @src rem.uo_orrr_rd 40e8824a | SimRISC-04 §乘除操作
; OBJ: {{[0-9a-f]+:}} 40 e8 82 4a{{.*}}rem.uo
; ASM: rem.uo rd8, rd9, rd10
rem.uo rd8, rd9, rd10

; @src rem.ut_orrr_rd 41e8824a | SimRISC-08 §乘除操作
; OBJ: {{[0-9a-f]+:}} 41 e8 82 4a{{.*}}rem.ut
; ASM: rem.ut rd8, rd9, rd10
rem.ut rd8, rd9, rd10

; @src rem.uw_orrr_rd 42e8824a | SimRISC-09 §乘除操作
; OBJ: {{[0-9a-f]+:}} 42 e8 82 4a{{.*}}rem.uw
; ASM: rem.uw rd8, rd9, rd10
rem.uw rd8, rd9, rd10

; @src shl.ub_orrr_rd 4350824a | SimRISC-10 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 43 50 82 4a{{.*}}shl.ub
; ASM: shl.ub rd8, rd9, rd10
shl.ub rd8, rd9, rd10

; @src shl.uo_orrr_rd 4050824a | SimRISC-04 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 40 50 82 4a{{.*}}shl.uo
; ASM: shl.uo rd8, rd9, rd10
shl.uo rd8, rd9, rd10

; @src shl.ut_orrr_rd 4150824a | SimRISC-08 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 41 50 82 4a{{.*}}shl.ut
; ASM: shl.ut rd8, rd9, rd10
shl.ut rd8, rd9, rd10

; @src shl.uw_orrr_rd 4250824a | SimRISC-09 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 42 50 82 4a{{.*}}shl.uw
; ASM: shl.uw rd8, rd9, rd10
shl.uw rd8, rd9, rd10

; @src shr.sb_orrr_rd 434c824a | SimRISC-10 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 43 4c 82 4a{{.*}}shr.sb
; ASM: shr.sb rd8, rd9, rd10
shr.sb rd8, rd9, rd10

; @src shr.so_orrr_rd 404c824a | SimRISC-04 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 40 4c 82 4a{{.*}}shr.so
; ASM: shr.so rd8, rd9, rd10
shr.so rd8, rd9, rd10

; @src shr.st_orrr_rd 414c824a | SimRISC-08 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 41 4c 82 4a{{.*}}shr.st
; ASM: shr.st rd8, rd9, rd10
shr.st rd8, rd9, rd10

; @src shr.sw_orrr_rd 424c824a | SimRISC-09 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 42 4c 82 4a{{.*}}shr.sw
; ASM: shr.sw rd8, rd9, rd10
shr.sw rd8, rd9, rd10

; @src shr.ub_orrr_rd 4348824a | SimRISC-10 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 43 48 82 4a{{.*}}shr.ub
; ASM: shr.ub rd8, rd9, rd10
shr.ub rd8, rd9, rd10

; @src shr.uo_orrr_rd 4048824a | SimRISC-04 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 40 48 82 4a{{.*}}shr.uo
; ASM: shr.uo rd8, rd9, rd10
shr.uo rd8, rd9, rd10

; @src shr.ut_orrr_rd 4148824a | SimRISC-08 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 41 48 82 4a{{.*}}shr.ut
; ASM: shr.ut rd8, rd9, rd10
shr.ut rd8, rd9, rd10

; @src shr.uw_orrr_rd 4248824a | SimRISC-09 §Bit manipulating：位操作指令
; OBJ: {{[0-9a-f]+:}} 42 48 82 4a{{.*}}shr.uw
; ASM: shr.uw rd8, rd9, rd10
shr.uw rd8, rd9, rd10

; @src sub.o_orrr_bbd 40c4824a | SimRISC-05 §加减操作
; OBJ: {{[0-9a-f]+:}} 40 c4 82 4a{{.*}}sub.o
; ASM: sub.o rb8, rb9, rd10
sub.o rb8, rb9, rd10

; @src sub.o_orrr_dbb 40cc824a | SimRISC-05 §加减操作
; OBJ: {{[0-9a-f]+:}} 40 cc 82 4a{{.*}}sub.o
; ASM: sub.o rd8, rb9, rb10
sub.o rd8, rb9, rb10

; @src sub.sb_orrr_rd 43a4824a | SimRISC-10 §加减操作
; OBJ: {{[0-9a-f]+:}} 43 a4 82 4a{{.*}}sub.sb
; ASM: sub.sb rd8, rd9, rd10
sub.sb rd8, rd9, rd10

; @src sub.st_orrr_rd 41a4824a | SimRISC-08 §加减操作
; OBJ: {{[0-9a-f]+:}} 41 a4 82 4a{{.*}}sub.st
; ASM: sub.st rd8, rd9, rd10
sub.st rd8, rd9, rd10

; @src sub.sw_orrr_rd 42a4824a | SimRISC-09 §加减操作
; OBJ: {{[0-9a-f]+:}} 42 a4 82 4a{{.*}}sub.sw
; ASM: sub.sw rd8, rd9, rd10
sub.sw rd8, rd9, rd10

; @src sub.ub_orrr_rd 43a0824a | SimRISC-10 §加减操作
; OBJ: {{[0-9a-f]+:}} 43 a0 82 4a{{.*}}sub.ub
; ASM: sub.ub rd8, rd9, rd10
sub.ub rd8, rd9, rd10

; @src sub.ut_orrr_rd 41a0824a | SimRISC-08 §加减操作
; OBJ: {{[0-9a-f]+:}} 41 a0 82 4a{{.*}}sub.ut
; ASM: sub.ut rd8, rd9, rd10
sub.ut rd8, rd9, rd10

; @src sub.uw_orrr_rd 42a0824a | SimRISC-09 §加减操作
; OBJ: {{[0-9a-f]+:}} 42 a0 82 4a{{.*}}sub.uw
; ASM: sub.uw rd8, rd9, rd10
sub.uw rd8, rd9, rd10

; @src xnor.o_orrr_rd 402c824a | SimRISC-04 §Logic operators：逻辑运算
; OBJ: {{[0-9a-f]+:}} 40 2c 82 4a{{.*}}xnor.o
; ASM: xnor.o rd8, rd9, rd10
xnor.o rd8, rd9, rd10

; @src xor.o_orrr_rd 4028824a | SimRISC-04 §Logic operators：逻辑运算
; OBJ: {{[0-9a-f]+:}} 40 28 82 4a{{.*}}xor.o
; ASM: xor.o rd8, rd9, rd10
xor.o rd8, rd9, rd10
