; ======================================================================
; GENERATED by tools/testcases/generate_lit_vectors.py — DO NOT EDIT
; lit MC 编码反例（scope: excluded 且汇编器不实现 ⇒ 须显式拒绝）
; 期望编码机械派生自 contracts/opcodes.yaml（op/value/mask/fields）；
; 无 llvm-mc/llc/QEMU 反填。重跑: python3 tools/testcases/generate_lit_vectors.py
; source: contracts/opcodes.yaml
; ======================================================================
; RUN: echo 'cfxld cfx63, [rb2, 1]' | %not %llvm_mc --triple=dadao-unknown-elf -filetype=obj -o /dev/null 2>&1 | %FileCheck %s --check-prefix=UNREC
; RUN: echo 'cfxst cfx63, [rb2, 1]' | %not %llvm_mc --triple=dadao-unknown-elf -filetype=obj -o /dev/null 2>&1 | %FileCheck %s --check-prefix=UNREC
; RUN: echo 'lr_an.o rd9, [rb1, 0]' | %not %llvm_mc --triple=dadao-unknown-elf -filetype=obj -o /dev/null 2>&1 | %FileCheck %s --check-prefix=UNREC
; RUN: echo 'lr_ar.o rd9, [rb1, 0]' | %not %llvm_mc --triple=dadao-unknown-elf -filetype=obj -o /dev/null 2>&1 | %FileCheck %s --check-prefix=UNREC
; RUN: echo 'lr_nn.o rd9, [rb1, 0]' | %not %llvm_mc --triple=dadao-unknown-elf -filetype=obj -o /dev/null 2>&1 | %FileCheck %s --check-prefix=UNREC
; RUN: echo 'lr_nr.o rd9, [rb1, 0]' | %not %llvm_mc --triple=dadao-unknown-elf -filetype=obj -o /dev/null 2>&1 | %FileCheck %s --check-prefix=UNREC
; RUN: echo 'sc_an.o rd8, rd9, [rb1, 0]' | %not %llvm_mc --triple=dadao-unknown-elf -filetype=obj -o /dev/null 2>&1 | %FileCheck %s --check-prefix=UNREC
; RUN: echo 'sc_ar.o rd8, rd9, [rb1, 0]' | %not %llvm_mc --triple=dadao-unknown-elf -filetype=obj -o /dev/null 2>&1 | %FileCheck %s --check-prefix=UNREC
; RUN: echo 'sc_nn.o rd8, rd9, [rb1, 0]' | %not %llvm_mc --triple=dadao-unknown-elf -filetype=obj -o /dev/null 2>&1 | %FileCheck %s --check-prefix=UNREC
; RUN: echo 'sc_nr.o rd8, rd9, [rb1, 0]' | %not %llvm_mc --triple=dadao-unknown-elf -filetype=obj -o /dev/null 2>&1 | %FileCheck %s --check-prefix=UNREC

.text
; UNREC: error: unrecognized instruction mnemonic

; @src cfxld_crii_cfx | SimRISC-00 §SimRISC QFC
; cfxld cfx63, [rb2, 1]（scope: excluded，汇编器 MUST 拒绝）

; @src cfxst_crii_cfx | SimRISC-00 §SimRISC QFC
; cfxst cfx63, [rb2, 1]（scope: excluded，汇编器 MUST 拒绝）

; @src lr_an.o_orrr_rd | SimRISC-12 §LR-SC指令
; lr_an.o rd9, [rb1, 0]（scope: excluded，汇编器 MUST 拒绝）

; @src lr_ar.o_orrr_rd | SimRISC-12 §LR-SC指令
; lr_ar.o rd9, [rb1, 0]（scope: excluded，汇编器 MUST 拒绝）

; @src lr_nn.o_orrr_rd | SimRISC-12 §LR-SC指令
; lr_nn.o rd9, [rb1, 0]（scope: excluded，汇编器 MUST 拒绝）

; @src lr_nr.o_orrr_rd | SimRISC-12 §LR-SC指令
; lr_nr.o rd9, [rb1, 0]（scope: excluded，汇编器 MUST 拒绝）

; @src sc_an.o_orrr_rd | SimRISC-12 §LR-SC指令
; sc_an.o rd8, rd9, [rb1, 0]（scope: excluded，汇编器 MUST 拒绝）

; @src sc_ar.o_orrr_rd | SimRISC-12 §LR-SC指令
; sc_ar.o rd8, rd9, [rb1, 0]（scope: excluded，汇编器 MUST 拒绝）

; @src sc_nn.o_orrr_rd | SimRISC-12 §LR-SC指令
; sc_nn.o rd8, rd9, [rb1, 0]（scope: excluded，汇编器 MUST 拒绝）

; @src sc_nr.o_orrr_rd | SimRISC-12 §LR-SC指令
; sc_nr.o rd8, rd9, [rb1, 0]（scope: excluded，汇编器 MUST 拒绝）
