; ======================================================================
; GENERATED by tools/testcases/generate_lit_vectors.py — DO NOT EDIT
; lit MC 编码正例
; 期望编码机械派生自 contracts/opcodes.yaml（op/value/mask/fields）；
; 无 llvm-mc/llc/QEMU 反填。重跑: python3 tools/testcases/generate_lit_vectors.py
; source: contracts/opcodes.yaml
; RUN: %llvm_mc --triple=dadao-unknown-elf -filetype=obj %s -o %t
; RUN: %llvm_objdump -d --triple=dadao-unknown-elf %t | %FileCheck %s --check-prefix=OBJ
; RUN: %llvm_mc --triple=dadao-unknown-elf -filetype=asm %s | %FileCheck %s --check-prefix=ASM
; ======================================================================

.text

; @src ldm.o_rrri_ra 3c200241 | SimRISC-01 §存取RA寄存器
; OBJ: {{[0-9a-f]+:}} 3c 20 02 41{{.*}}ldm.o
; ASM: ldm.o {ra8}, [rb0, rd9]
ldm.o {ra8}, [rb0, rd9]

; @src ldm.o_rrri_rb 3a200241 | SimRISC-01 §存取RB寄存器
; OBJ: {{[0-9a-f]+:}} 3a 20 02 41{{.*}}ldm.o
; ASM: ldm.o {rb8}, [rb0, rd9]
ldm.o {rb8}, [rb0, rd9]

; @src ldm.o_rrri_rd 38200241 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 38 20 02 41{{.*}}ldm.o
; ASM: ldm.o {rd8}, [rb0, rd9]
ldm.o {rd8}, [rb0, rd9]

; @src ldm.o_rrri_rf 3e200241 | SimRISC-00 §SimRISC QFC
; OBJ: {{[0-9a-f]+:}} 3e 20 02 41{{.*}}ldm.o
; ASM: ldm.o {rf8}, [rb0, rd9]
ldm.o {rf8}, [rb0, rd9]

; @src ldm.sb_rrri_rd 2b200241 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 2b 20 02 41{{.*}}ldm.sb
; ASM: ldm.sb {rd8}, [rb0, rd9]
ldm.sb {rd8}, [rb0, rd9]

; @src ldm.st_rrri_rd 2d200241 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 2d 20 02 41{{.*}}ldm.st
; ASM: ldm.st {rd8}, [rb0, rd9]
ldm.st {rd8}, [rb0, rd9]

; @src ldm.sw_rrri_rd 2c200241 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 2c 20 02 41{{.*}}ldm.sw
; ASM: ldm.sw {rd8}, [rb0, rd9]
ldm.sw {rd8}, [rb0, rd9]

; @src ldm.t_rrri_rf 2e200241 | SimRISC-00 §SimRISC QFC
; OBJ: {{[0-9a-f]+:}} 2e 20 02 41{{.*}}ldm.t
; ASM: ldm.t {rf8}, [rb0, rd9]
ldm.t {rf8}, [rb0, rd9]

; @src ldm.ub_rrri_rd 28200241 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 28 20 02 41{{.*}}ldm.ub
; ASM: ldm.ub {rd8}, [rb0, rd9]
ldm.ub {rd8}, [rb0, rd9]

; @src ldm.ut_rrri_rd 2a200241 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 2a 20 02 41{{.*}}ldm.ut
; ASM: ldm.ut {rd8}, [rb0, rd9]
ldm.ut {rd8}, [rb0, rd9]

; @src ldm.uw_rrri_rd 29200241 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 29 20 02 41{{.*}}ldm.uw
; ASM: ldm.uw {rd8}, [rb0, rd9]
ldm.uw {rd8}, [rb0, rd9]

; @src stm.b_rrri_rd 30200241 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 30 20 02 41{{.*}}stm.b
; ASM: stm.b {rd8}, [rb0, rd9]
stm.b {rd8}, [rb0, rd9]

; @src stm.o_rrri_ra 3d200241 | SimRISC-01 §存取RA寄存器
; OBJ: {{[0-9a-f]+:}} 3d 20 02 41{{.*}}stm.o
; ASM: stm.o {ra8}, [rb0, rd9]
stm.o {ra8}, [rb0, rd9]

; @src stm.o_rrri_rb 3b200241 | SimRISC-01 §存取RB寄存器
; OBJ: {{[0-9a-f]+:}} 3b 20 02 41{{.*}}stm.o
; ASM: stm.o {rb8}, [rb0, rd9]
stm.o {rb8}, [rb0, rd9]

; @src stm.o_rrri_rd 39200241 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 39 20 02 41{{.*}}stm.o
; ASM: stm.o {rd8}, [rb0, rd9]
stm.o {rd8}, [rb0, rd9]

; @src stm.o_rrri_rf 3f200241 | SimRISC-00 §SimRISC QFC
; OBJ: {{[0-9a-f]+:}} 3f 20 02 41{{.*}}stm.o
; ASM: stm.o {rf8}, [rb0, rd9]
stm.o {rf8}, [rb0, rd9]

; @src stm.t_rrri_rd 32200241 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 32 20 02 41{{.*}}stm.t
; ASM: stm.t {rd8}, [rb0, rd9]
stm.t {rd8}, [rb0, rd9]

; @src stm.t_rrri_rf 2f200241 | SimRISC-00 §SimRISC QFC
; OBJ: {{[0-9a-f]+:}} 2f 20 02 41{{.*}}stm.t
; ASM: stm.t {rf8}, [rb0, rd9]
stm.t {rf8}, [rb0, rd9]

; @src stm.w_rrri_rd 31200241 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 31 20 02 41{{.*}}stm.w
; ASM: stm.w {rd8}, [rb0, rd9]
stm.w {rd8}, [rb0, rd9]
