; ======================================================================
; GENERATED by tools/testcases/generate_lit_vectors.py — DO NOT EDIT
; lit MC 编码正例
; 期望编码机械派生自 contracts/opcodes.yaml（op/value/mask/fields）；
; 无 llvm-mc/llc/QEMU 反填。重跑: python3 tools/testcases/generate_lit_vectors.py
; source: contracts/opcodes.yaml
; RUN: %llvm_mc --triple=dadao-unknown-elf -filetype=obj %s -o %t
; RUN: %llvm_objdump -d --triple=dadao-unknown-elf %t | %FileCheck %s --check-prefix=OBJ
; RUN: %llvm_mc --triple=dadao-unknown-elf -filetype=asm %s | %FileCheck %s --check-prefix=ASM
; ======================================================================

.text

; @src call_iiii_ra 74000003 | SimRISC-06 §函数调用
; OBJ: {{[0-9a-f]+:}} 74 00 00 03{{.*}}call
; ASM: call [rb0, 12]
call [rb0, 12]

; @src jump_iiii_rb 70000003 | SimRISC-06 §无条件跳转指令
; OBJ: {{[0-9a-f]+:}} 70 00 00 03{{.*}}jump
; ASM: jump [rb0, 12]
jump [rb0, 12]
