; ======================================================================
; GENERATED by tools/testcases/generate_lit_vectors.py — DO NOT EDIT
; lit MC 编码正例
; 期望编码机械派生自 contracts/opcodes.yaml（op/value/mask/fields）；
; 无 llvm-mc/llc/QEMU 反填。重跑: python3 tools/testcases/generate_lit_vectors.py
; source: contracts/opcodes.yaml
; RUN: %llvm_mc --triple=dadao-unknown-elf -filetype=obj %s -o %t
; RUN: %llvm_objdump -d --triple=dadao-unknown-elf %t | %FileCheck %s --check-prefix=OBJ
; RUN: %llvm_mc --triple=dadao-unknown-elf -filetype=asm %s | %FileCheck %s --check-prefix=ASM
; ======================================================================

.text

; @src escape_ciii_cfx 7efc0002 | SimRISC-00 §SimRISC QFC
; OBJ: {{[0-9a-f]+:}} 7e fc 00 02{{.*}}escape
; ASM: escape cfx63, [excp_cause_ip, 8]
escape cfx63, [excp_cause_ip, 8]

; @src trap_ciii_cfx 7ffc0001 | SimRISC-00 §SimRISC QFC
; OBJ: {{[0-9a-f]+:}} 7f fc 00 01{{.*}}trap
; ASM: trap cfx63, 1
trap cfx63, 1
