; ======================================================================
; GENERATED by tools/testcases/generate_lit_vectors.py — DO NOT EDIT
; lit MC 编码正例
; 期望编码机械派生自 contracts/opcodes.yaml（op/value/mask/fields）；
; 无 llvm-mc/llc/QEMU 反填。重跑: python3 tools/testcases/generate_lit_vectors.py
; source: contracts/opcodes.yaml
; RUN: %llvm_mc --triple=dadao-unknown-elf -filetype=obj %s -o %t
; RUN: %llvm_objdump -d --triple=dadao-unknown-elf %t | %FileCheck %s --check-prefix=OBJ
; RUN: %llvm_mc --triple=dadao-unknown-elf -filetype=asm %s | %FileCheck %s --check-prefix=ASM
; ======================================================================

.text

; @src br.eq_rrii_rd 6e209004 | SimRISC-06 §条件跳转指令
; OBJ: {{[0-9a-f]+:}} 6e 20 90 04{{.*}}br.eq
; ASM: br.eq {rd8, rd9}?, [rb0, 16]
br.eq {rd8, rd9}?, [rb0, 16]

; @src br.ne_rrii_rd 6f209004 | SimRISC-06 §条件跳转指令
; OBJ: {{[0-9a-f]+:}} 6f 20 90 04{{.*}}br.ne
; ASM: br.ne {rd8, rd9}?, [rb0, 16]
br.ne {rd8, rd9}?, [rb0, 16]

; @src call_rrii_ra 75209018 | SimRISC-06 §函数调用
; OBJ: {{[0-9a-f]+:}} 75 20 90 18{{.*}}call
; ASM: call [rb8, rd9, 96]
call [rb8, rd9, 96]

; @src cmp.si_rrii_rd 5d209001 | SimRISC-04 §比较操作
; OBJ: {{[0-9a-f]+:}} 5d 20 90 01{{.*}}cmp.si
; ASM: cmp.si rd8, rd9, 1
cmp.si rd8, rd9, 1

; @src cmp.ui_rrii_rd 5c209001 | SimRISC-04 §比较操作
; OBJ: {{[0-9a-f]+:}} 5c 20 90 01{{.*}}cmp.ui
; ASM: cmp.ui rd8, rd9, 1
cmp.ui rd8, rd9, 1

; @src jump_rrii_rb 71209018 | SimRISC-06 §无条件跳转指令
; OBJ: {{[0-9a-f]+:}} 71 20 90 18{{.*}}jump
; ASM: jump [rb8, rd9, 96]
jump [rb8, rd9, 96]

; @src ld.o_rrii_ra 24209008 | SimRISC-01 §存取RA寄存器
; OBJ: {{[0-9a-f]+:}} 24 20 90 08{{.*}}ld.o
; ASM: ld.o ra8, [rb9, 8]
ld.o ra8, [rb9, 8]

; @src ld.o_rrii_rb 22209008 | SimRISC-01 §存取RB寄存器
; OBJ: {{[0-9a-f]+:}} 22 20 90 08{{.*}}ld.o
; ASM: ld.o rb8, [rb9, 8]
ld.o rb8, [rb9, 8]

; @src ld.o_rrii_rd 20209008 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 20 20 90 08{{.*}}ld.o
; ASM: ld.o rd8, [rb9, 8]
ld.o rd8, [rb9, 8]

; @src ld.o_rrii_rf 26209001 | SimRISC-00 §SimRISC QFC
; OBJ: {{[0-9a-f]+:}} 26 20 90 01{{.*}}ld.o
; ASM: ld.o rf8, [rb9, 1]
ld.o rf8, [rb9, 1]

; @src ld.sb_rrii_rd 13209001 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 13 20 90 01{{.*}}ld.sb
; ASM: ld.sb rd8, [rb9, 1]
ld.sb rd8, [rb9, 1]

; @src ld.st_rrii_rd 15209004 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 15 20 90 04{{.*}}ld.st
; ASM: ld.st rd8, [rb9, 4]
ld.st rd8, [rb9, 4]

; @src ld.sw_rrii_rd 14209002 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 14 20 90 02{{.*}}ld.sw
; ASM: ld.sw rd8, [rb9, 2]
ld.sw rd8, [rb9, 2]

; @src ld.t_rrii_rf 16209001 | SimRISC-00 §SimRISC QFC
; OBJ: {{[0-9a-f]+:}} 16 20 90 01{{.*}}ld.t
; ASM: ld.t rf8, [rb9, 1]
ld.t rf8, [rb9, 1]

; @src ld.ub_rrii_rd 10209001 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 10 20 90 01{{.*}}ld.ub
; ASM: ld.ub rd8, [rb9, 1]
ld.ub rd8, [rb9, 1]

; @src ld.ut_rrii_rd 12209004 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 12 20 90 04{{.*}}ld.ut
; ASM: ld.ut rd8, [rb9, 4]
ld.ut rd8, [rb9, 4]

; @src ld.uw_rrii_rd 11209002 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 11 20 90 02{{.*}}ld.uw
; ASM: ld.uw rd8, [rb9, 2]
ld.uw rd8, [rb9, 2]

; @src st.b_rrii_rd 18209001 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 18 20 90 01{{.*}}st.b
; ASM: st.b rd8, [rb9, 1]
st.b rd8, [rb9, 1]

; @src st.o_rrii_ra 25209008 | SimRISC-01 §存取RA寄存器
; OBJ: {{[0-9a-f]+:}} 25 20 90 08{{.*}}st.o
; ASM: st.o ra8, [rb9, 8]
st.o ra8, [rb9, 8]

; @src st.o_rrii_rb 23209008 | SimRISC-01 §存取RB寄存器
; OBJ: {{[0-9a-f]+:}} 23 20 90 08{{.*}}st.o
; ASM: st.o rb8, [rb9, 8]
st.o rb8, [rb9, 8]

; @src st.o_rrii_rd 21209008 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 21 20 90 08{{.*}}st.o
; ASM: st.o rd8, [rb9, 8]
st.o rd8, [rb9, 8]

; @src st.o_rrii_rf 27209001 | SimRISC-00 §SimRISC QFC
; OBJ: {{[0-9a-f]+:}} 27 20 90 01{{.*}}st.o
; ASM: st.o rf8, [rb9, 1]
st.o rf8, [rb9, 1]

; @src st.t_rrii_rd 1a209004 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 1a 20 90 04{{.*}}st.t
; ASM: st.t rd8, [rb9, 4]
st.t rd8, [rb9, 4]

; @src st.t_rrii_rf 17209001 | SimRISC-00 §SimRISC QFC
; OBJ: {{[0-9a-f]+:}} 17 20 90 01{{.*}}st.t
; ASM: st.t rf8, [rb9, 1]
st.t rf8, [rb9, 1]

; @src st.w_rrii_rd 19209002 | SimRISC-01 §存取RD寄存器
; OBJ: {{[0-9a-f]+:}} 19 20 90 02{{.*}}st.w
; ASM: st.w rd8, [rb9, 2]
st.w rd8, [rb9, 2]
