; ======================================================================
; GENERATED by tools/testcases/generate_lit_vectors.py — DO NOT EDIT
; lit MC 编码正例
; 期望编码机械派生自 contracts/opcodes.yaml（op/value/mask/fields）；
; 无 llvm-mc/llc/QEMU 反填。重跑: python3 tools/testcases/generate_lit_vectors.py
; source: contracts/opcodes.yaml
; RUN: %llvm_mc --triple=dadao-unknown-elf -filetype=obj %s -o %t
; RUN: %llvm_objdump -d --triple=dadao-unknown-elf %t | %FileCheck %s --check-prefix=OBJ
; RUN: %llvm_mc --triple=dadao-unknown-elf -filetype=asm %s | %FileCheck %s --check-prefix=ASM
; ======================================================================

.text

; @src fence_oiii_imm 77000000 | SimRISC-12 §fence指令
; OBJ: {{[0-9a-f]+:}} 77 00 00 00{{.*}}fence
; ASM: fence 0
fence 0

; @src swym_oiii_imm 77880008 | SimRISC-11 §占位指令
; OBJ: {{[0-9a-f]+:}} 77 88 00 08{{.*}}swym
; ASM: swym 8
swym 8
