; ======================================================================
; GENERATED by tools/testcases/generate_lit_vectors.py — DO NOT EDIT
; lit MC 编码正例
; 期望编码机械派生自 contracts/opcodes.yaml（op/value/mask/fields）；
; 无 llvm-mc/llc/QEMU 反填。重跑: python3 tools/testcases/generate_lit_vectors.py
; source: contracts/opcodes.yaml
; RUN: %llvm_mc --triple=dadao-unknown-elf -filetype=obj %s -o %t
; RUN: %llvm_objdump -d --triple=dadao-unknown-elf %t | %FileCheck %s --check-prefix=OBJ
; RUN: %llvm_mc --triple=dadao-unknown-elf -filetype=asm %s | %FileCheck %s --check-prefix=ASM
; ======================================================================

.text

; @src cfx2rc_crrr_cfx 7bfc8048 | SimRISC-00 §SimRISC QFC
; OBJ: {{[0-9a-f]+:}} 7b fc 80 48{{.*}}cfx2rc
; ASM: cfx2rc cfx63, cg8, rc1, rd8
cfx2rc cfx63, cg8, rc1, rd8

; @src cfx2rd_crrr_cfx 7afc8048 | SimRISC-00 §SimRISC QFC
; OBJ: {{[0-9a-f]+:}} 7a fc 80 48{{.*}}cfx2rd
; ASM: cfx2rd cfx63, cg8, rc1, rd8
cfx2rd cfx63, cg8, rc1, rd8
